### ISSUE TITLE
Please provide more info on return types from execute

### ISSUE THREAD

**Issue by songololo** [supabase-community/supabase-py#115]
The return types from execute currently require trial and error to unpack. Would it be possible to add more information in the README.md explaining what the potential return types are and what they mean?

e.g. the returned value seems to have changed from a prior version of `postgrest-py`: it now returns a tuple of data and a `None` value. But it isn't clear what this `None` value represents and how to handle potential response errors on the return types?

**Comment by dreinon** [comment]
Hi! Thanks for reporting. We have an [open PR](https://github.com/supabase-community/postgrest-py/pull/64) to solve this, which only needs a few tests to be written

**Comment by dreinon** [comment]
Btw, that None value is intended to be the `count` value if you ask for it in the query.

**Comment by dannmate** [comment]
I am finding the return types are different also from selecting data, to inserting/updating, looking forward to the PR :)

**Comment by dreinon** [comment]
Hi! This issue should be solved with the new version of postgrest-py and supabase-py, we use a pydantic model now to represent a Response, which has two properties, data and count, and you'll get an APIError raised if the call returns an error 🙂.

Thanks!
