### ISSUE TITLE
bug: no module named `realtime.connection; realtime` is not a package

### ISSUE THREAD

**Issue by alif-arrizqy** [supabase-community/supabase-py#119]
I have an error like this when using this package.
ModuleNotFoundError: No module named 'realtime.connection'; 'realtime' is not a package

anyone can help me

**Comment by leynier** [comment]
Hi @alif-arrizqy, can you show us an example code snippet that raises this error.

**Comment by alif-arrizqy** [comment]
Hi @leynier 
previously I wasn't using the 0.2.0 version (I forgot the supabase version) and it still worked.
but when I install/upgrade to version 0.2.0, then this error appears.

I tried to create a new folder and install the latest version of supabase (v0.2.0) and it worked. I think there is a conflict between the old and new files

here the code:
``` python

from supabase import create_client, Client

supabase_url = "url_supabase"
supabase_key = "key_supabase"

if __name__ == "__main__":
    sb: Client = create_client(supabase_url, supabase_key)
    data = (
        sb.table("melawai_hourly_graph")
        .select("harvest_ratio")
        .order(column="jam", desc=False)
        .execute()
    )

    print(data)

```

here the error:
![image](https://user-images.githubusercontent.com/45624651/149860703-8a248be7-29e0-48d1-beb6-da79ba160e5f.png)

**Comment by anand2312** [comment]
This has been fixed in the later versions. The problematic import was removed.
