### ISSUE TITLE
Update README with the new API

### ISSUE THREAD

**Issue by nikeshnaik** [supabase-community/supabase-py#139]
**Describe the bug**
In the ReadMe.md file, the examples shown for inserting data, selecting data from the `countries` table returns `class` object, an assertion on that object to get `data` is throwing error.  Is doc outdated?

**To Reproduce**
Steps to reproduce the behaviour:
Run the examples shown in ReadMe.md

`    assert len(data.get("data", [])) > 0
AttributeError: 'APIResponse' object has no attribute 'get'`

**Expected behaviour**
`supabase: Client = create_client(url, key)
data = supabase.table("countries").select("*").execute()
_Assert we pulled real data._
assert len(**data.get("data", []**)) > 0   ----> Throwing error

supabase: Client = create_client(url, key)
data = supabase.table("countries").select("*").execute()
_Assert we pulled real data._
assert len(**data.data**) > 0` --> This fixes it, shall I update remaining examples.

**Comment by dreinon** [comment]
Yet to be updated! Forgot to update it, sorry
