### ISSUE TITLE
Unorderd Table Items

### ISSUE THREAD

**Issue by KineticFox** [supabase-community/supabase-py#191]
**Describe the bug**
If u get Data from a table with ```client.select('*').execute()``` the returned data is not in order. The table items are not in the same order as they are in the table.
For  example in the JS Framework the returned items from .select() are in the same order as in the table.

**To Reproduce**
1. create table with few items
2. on the client side use ```client.table('xyz').select('*').execute()```
3. compare the returned order of items with the table
4. See difference 

**Expected behavior**
Return the items from a table in the same way they appear in supabase table view

**Additional context**
I'm not sure if it is your intention to not return them in the same order and let the user sort the returned items.

**Comment by anand2312** [comment]
Personally, I don't believe it is the responsibility of the library to order results in any way, when you haven't mentioned any specific order to sort by (`select().order('column', desc=True).execute()` for example)

**Comment by KineticFox** [comment]
I understand, so i'm just spoiled by the official JS framework.

**Comment by anand2312** [comment]
Even if the js client does it I wouldn't rely on that ordering :p That should be considered an implementation detail that is not guaranteed to be changed in the future
I hope that answers your question!

**Comment by GaryAustin1** [comment]
Just to point out the javascript client does not do any default ordering and neither does Postgres.  All data can be random between reads (usually not if on same page on the disk) but if you page you will get duplicates.
