### ISSUE TITLE
JWSError JWSInvalidSignature

### ISSUE THREAD

**Issue by TiannV** [supabase-community/supabase-py#195]
**Describe the bug**
Follow https://github.com/supabase-community/supabase-py, I can run sign_in, but select failed。

![image](https://user-images.githubusercontent.com/36880544/164590536-3c26e7e5-4f32-4091-8ab8-4613ed865cfe.png)
![image](https://user-images.githubusercontent.com/36880544/164590559-d8d6d02a-34a6-469f-8304-92a51ff2b4fe.png)

sign_up.py:
```
import os
from supabase import create_client, Client

url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_KEY")
supabase: Client = create_client(url, key)
# Sign in using the user email and password.
random_email: str = "tianweistyle@gmail.com"
random_password: str = "fqj13bnf2hiu23h"
user = supabase.auth.sign_in(email=random_email, password=random_password)
print(user)
```

query.py:
```
import os
from supabase import create_client, Client

url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_KEY")
supabase: Client = create_client(url, key)
data = supabase.table("countries").select("*").execute()
print(data)
# Assert we pulled real data.
assert len(data.get("data", [])) > 0
```

**Comment by anand2312** [comment]
I doubt this is an issue with the library. This is most likely an issue with your auth key, recheck and make sure you are using the right one. Refer https://github.com/PostgREST/postgrest/issues/977
