### ISSUE TITLE
text filed eq filter not working 

### ISSUE THREAD

**Issue by wanghaisheng** [supabase-community/supabase-py#196]
**Describe the bug**
before insert  i want to check whether this text filed uid is exist, but even insert before,filter query give me []

**To Reproduce**
Successfully installed gotrue-0.5.0 postgrest-py-0.9.2 supabase-0.5.3
python 3.8.5

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows

**Smartphone (please complete the following information):**

**Additional context**

```
                for i in items:
                    uid=i['user_info']['uid'].strip()
                    print('this uid',uid)
                    data = supabase_db.table("tiktoka_douyin_users").select('uid').eq("uid",uid).execute()
                    print('existing db',len(supabase_db.table("tiktoka_douyin_users").select('uid').execute()[0]),data,data[0])
                    if len(data[0])>0:
                        print('this user exist',data[0])
                    else:
                        user={}

                        user['uid']=i['user_info']['uid'].strip()


                        data = supabase_db.table("tiktoka_douyin_users").insert(user).execute()
```

**Comment by wanghaisheng** [comment]
![firefox_SK8GfcyHh6](https://user-images.githubusercontent.com/2363295/164614362-cc33b457-d734-4bbb-947d-5390c1c0da1e.png)

**Comment by anand2312** [comment]
Can you explain what the issue is? I don't quite understand

**Comment by wanghaisheng** [comment]
i  dont want duplicate insert  ,i use uid as a check condition ,as you can see in the picture, we insert it fourth.
the problem came from here, every insert i manually query whether this uid exists,but constantly  i get a  [] even if i can browse this item in supabase portal

                    data = supabase_db.table("tiktoka_douyin_users").select('uid').eq("uid",uid).execute()
                    print('existing db',len(supabase_db.table("tiktoka_douyin_users").select('uid').execute()[0]),data,data[0])
                    if len(data[0])>0:

**Comment by anand2312** [comment]
Why not just apply a constraint at the database level (a UNIQUE constraint on the uid column) instead of manually checking for existence?

**Comment by wanghaisheng** [comment]
i get it

the weired thing is select and filter thing does not work

**Comment by anand2312** [comment]
Odd, I cannot reproduce this (selects and eq works as expected) which makes me think perhaps the values you are passing to the filters are incorrect.
Can you enable debug logging and show the HTTP requests that are being sent? https://postgrest-py.readthedocs.io/en/latest/examples/logging.html

**Comment by anand2312** [comment]
I also think you are on an old version of postgrest-py/supabase-py, subscripting on the result (i.e `supabase_db.table("tiktoka_douyin_users").select('uid').execute()[0]`) would error on postgrest-py now, as the `.execute()` method returns a pydantic model, not a list or dict that can be subscripted.

**Comment by wanghaisheng** [comment]
yes  after re uninstall postgrest-py  and  supabase ,install twice ,it works for now
