### ISSUE TITLE
AttributeError: 'RequestBuilder' object has no attribute 'on'

### ISSUE THREAD

**Issue by iwootten** [supabase-community/supabase-py#20]
# Bug report

## Describe the bug

The Python client doesn't support realtime subscription and fails with "AttributeError: 'RequestBuilder' object has no attribute 'on'".

(Update 17/01/22: This was an example originally forming part of the README)

## To Reproduce

Using the following example from the original readme:

```python 
subscription = supabase.table("countries").on("*", lambda x: print(x)).subscribe()`
```

## Expected behavior

For each postgres db change to be printed.

## System information

- MacOS 11.3 Beta
- Version of supabase-js: [0.0.2]
- Version of Node.js: [N/A - Using hosted]

**Comment by abreumatheus** [comment]
Code responsible for realtime features is commented, for some reason.

**Comment by sureshdsk** [comment]
any idea why this is disabled?

**Comment by iwootten** [comment]
I've just hit this issue again, 9 months later when starting a new project. It's confusing that this example is in the documentation when it .

**Comment by J0** [comment]
Hey @iwootten,

Thanks for bumping this! We're sorry that you had to face the error twice in a row D: We'll remove the example from the documentation.

Thanks!
Joel

**Comment by iwootten** [comment]
Actually, I'll update the description given this is still an issue.

**Comment by J0** [comment]
Gotcha. Thanks!

**Comment by chitalian** [comment]
This still seems to be an issue. The README still show `on` as a function however it is disabled in the API itself

**Comment by J0** [comment]
Hey @chitalian,

Do you mind pointing me to the relevant section of the README?Can't seem to find it in Supabase-py
