### ISSUE TITLE
End to End Integration Tests

### ISSUE THREAD

**Issue by J0** [supabase-community/supabase-py#207]
**Is your feature request related to a problem? Please describe.**

As part of an ongoing effort to get an overview of where the different client libraries are at(with respect to js client) the Supabase QA team(@egor-romanov) has kindly set up [a set of integration tests](https://github.com/supabase/infrastructure/tree/feature/verification-tests/tests)

I'm setting up this issue to keep track of where we're at and also to note and patch existing bugs

To Patch:
- [ ] Auth
- [ ] Storage
- [ ] Functions
- [ ] More to come

**Additional context**

**Comment by kareemmahlees** [comment]
@J0 Hey the link you provided is broken may be update it!

**Comment by J0** [comment]
Hey @kareemmahlees, we're putting together a new set of tests will circle back once they're up but tag me if I forget to get back

**Comment by silentworks** [comment]
Closing this out as each project has their own tests and we now have a board to track features/bugs of each project https://github.com/orgs/supabase-community/projects/1/views/4
