### ISSUE TITLE
`.table` and `.from_` return type is wrong

### ISSUE THREAD

**Issue by mr-bjerre** [supabase-community/supabase-py#211]
The return type for `Client.table` and `Client.from_` is forced to `SupabaseQueryBuilder`. It should be removed and then the return type will be inferred to `RequestBuilder`.

**Comment by mr-bjerre** [comment]
I just realized that poetry installed 0.2.0 instead of 0.5.6. Looking in the source code it seems this is no longer an issue.

But how come it's not possible to install 0.5.6 with poetry?

```
> poetry add supabase-py==0.5.6 --optional --allow-prereleases

  ValueError

  Could not find a matching version of package supabase-py
```

I'm on python 3.9

**Comment by dreinon** [comment]
Supabase-py changed the package name to supabase, try poetry add supabase==0.5.6

**Comment by mr-bjerre** [comment]
```
poetry add supabase
```
instead of 
```
poetry add supabase-py
```
