### ISSUE TITLE
Client does not use alternative schema when provided

### ISSUE THREAD

**Issue by Morioki** [supabase-community/supabase-py#217]
**Describe the bug**
Client does not pass schema to the initialization of the SyncPostgresClient object. This causes any call to the database to assume that the default public database is used instead of the provided schema. 

**To Reproduce**
1. Create a table in an alternate schema, where a table does not exist with the same name in the public schema.
2. Create a client object using the create_client() function and provide it an alternative schema in the ClientOptions dict.
3. Query the table or attempt an insert into the table

**Expected behavior**
Table is queried / inserted into properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/4792427/171561302-ad90f332-c41c-4a75-a203-1de4606148b5.png)

supabase-py version 0.5.6

**Available Workaround**
It is possible to currently call the schema function on the postgrest object within the client object in order to properly set the schema. 
ex: supabase.postgrest.schema('alternateSchema')

**Comment by anand2312** [comment]
Thanks for the report. Would you like to make a bug-fix PR? I'd be happy to review and merge
