### ISSUE TITLE
Authentification headers when using storage client

### ISSUE THREAD

**Issue by tobias-scheepers** [supabase-community/supabase-py#247]
Currently (`v0.5.8`) it seems when uploading a file to an bucket there are no authentication credentials passed along from the main supabase client. As such I've only gotten uploading to a public bucket (and setting the storage.object table to non RLS) to work. Is there any way to upload a file to a private bucket that is currently supported by supabase-py?

**Comment by anand2312** [comment]
We haven't yet written the code to automatically set the auth credentials on the sub-clients
For now you could manually set them with something like
```py
client = create_client(SUPABASE_URL, SUPABASE_KEY)
session = client.auth.sign_in(email, password)

storage = client.storage()
storage._client.headers["Authentication"] = f"Bearer {session.access_token}" 

# run queries
client.auth.sign_out()
storage._client.headers["Authentication"] = f"Bearer {SUPABASE_KEY}" # go back to using the anon key
```

**Comment by anand2312** [comment]
(If I'm remembering right, you'd opened a similar issue with postgrest where I'd said I was working on it 😅 sadly I've gotten a bit busy since then and that hasn't been pushed upstream yet either)

**Comment by tobias-scheepers** [comment]
Hi @anand2312, thanks again for the quick help! Indeed that was me. I could not for the life of me find the old comment on postgrest. However, same solution goes here and this will work perfectly fine! Thanks again for all the amazing work on these tools!
