### ISSUE TITLE
Is this repo compatible with async?

### ISSUE THREAD

**Issue by Pixeled99** [supabase-community/supabase-py#249]
I have been trying to use supabase in my async python code. I've found 1 small library that hasn't been updated in a year and is also giving me problems. So I was wondering if there was any async support for this library. If there isn't I think it would be a great addition. As I pretty desperately need a way to interact with supabase in async code. Also if it's not supported does anyone know any async python libraries to interact with supabase? https://github.com/keosariel/supabase-client is the only one I've found and as said earlier it doesn't work too well.

**Comment by akherlan** [comment]
Could you give a hint how to work with async technique in Python for Supabase library? @Pixeled99
