### ISSUE TITLE
Extra / in storage get_public_url() method

### ISSUE THREAD

**Issue by justinbarak** [supabase-community/supabase-py#261]
**Describe the bug**
There is an extra forward slash returned in the get_public_url method.

**To Reproduce**
1. Instantiate SupabaseStorageClient
2. Use client.from_({bucket}).get_public_url({filename})
3. Result is 'https://{database}.supabase.co/storage/v1//object/public/{bucket}/{filename}'

**Expected behavior**
'https://{database}.supabase.co/storage/v1/object/public/{bucket}/{filename}' which matches what you get from the supabase website console when clicking the button for public_url.

**Desktop (please complete the following information):**
 - OS: Windows11
 - Python: 3.9.9
 - Supabase version: 0.5.8

**Additional context**
Deleting the extra / between v1 and object does give the correct url.

**Comment by ZetiMente** [comment]
Can you use this package for Supabase storage ?

**Comment by justinbarak** [comment]
> Can you use this package for Supabase storage ?

I think that's how you're supposed to access it via python. It builds off of [another package](https://pypi.org/project/storage3/), which specifically recommends using this 'master' package to interact with the storage api.

**Comment by anand2312** [comment]
Would you like to open a bug-fix PR? You'd just need to remove the `/` before `object` on [this line](https://github.com/supabase-community/storage-py/blob/6ca09e7b4cff12112599e2a1ea714f6f5f6af453/storage3/_async/file_api.py#L75) I think. (It looks like `base_url` has a trailing `\`, looking at the implementation of `create_signed_url` above this method).

**Comment by justinbarak** [comment]
> Would you like to open a bug-fix PR? You'd just need to remove the `/` before `object` on [this line](https://github.com/supabase-community/storage-py/blob/6ca09e7b4cff12112599e2a1ea714f6f5f6af453/storage3/_async/file_api.py#L75) I think. (It looks like `base_url` has a trailing `/`, looking at the implementation of `create_signed_url` above this method).

Done! Feel free to review and approve. Thanks for finding the line in issue!!

**Comment by justinbarak** [comment]
@anand2312 Can you review and approve?

**Comment by justinbarak** [comment]
Any way to get this pull request integrated? It is the most minor of corrections and won't cause issues.

**Comment by anand2312** [comment]
Merged the PR, this will be updated here in the next version. Thanks for your contribution!
