### ISSUE TITLE
How can I confirm Email Addresses

### ISSUE THREAD

**Issue by TheMG95** [supabase-community/supabase-py#285]

**Comment by TheMG95** [comment]
Accidentally clicked enter sorry,
Well i was gonna ask how can i use the email account verification?

**Comment by J0** [comment]
No worries, could you provide more details on what sort of workflow you're hoping to use with email account verification? Are you perhaps looking to implement magic link sign in or similar?

One way to enforce email verification would be t call `supabase.auth.signup()` and then ensure you have correctly configured the settings under Authentication > Settings > Email  and click Enable Email confirmation to ensure that users are only verified after they confirm/verify their emails

**Comment by TheMG95** [comment]
Sorry for not being clear. I wanted to ask, how can I confirm email addresses? When i do supabase.auth.signup() the email sent has a localhost link and a key. Do i have to handle that in my server? If so, how can i do that?

**Comment by TheMG95** [comment]
Also how can i use the hcaptcha protection?
![image](https://user-images.githubusercontent.com/66237187/194923650-f88f3f78-7512-4ca6-b1b9-681fa2b24c7e.png)

**Comment by J0** [comment]
When you click on the link sent to your email a request is sent to Supabase Auth to verify the token in the link. The user is then marked as confirmed and redirected to your site .


For HCaptcha, you can take a look at [this guide](https://supabase.com/docs/guides/auth/auth-captcha) and we will also have video tutorials coming soon.

Hope this helps and let us know if you have further questions

**Comment by TheMG95** [comment]
Thanks a lot!
