### ISSUE TITLE
How can i add data to user on creation?

### ISSUE THREAD

**Issue by TheMG95** [supabase-community/supabase-py#288]
I want to add some data to users on sign up like a username. How can i do this?

**Comment by J0** [comment]
Hey, 

Thanks for your patience - you can add data via using the [`data` param](https://github.com/supabase-community/gotrue-py/blob/main/gotrue/_async/client.py#L98) on `sign_up` which will add metadata to the field.

We're putting together some docs so hopefully this should be clearer soon.

**Comment by JeremyBrent** [comment]
I am having issues with this. Was this a breaking change or am I missing something?
