### ISSUE TITLE
'Error in $: not enough input' on .update()

### ISSUE THREAD

**Issue by rphly** [supabase-community/supabase-py#30]
# Bug report

## To Reproduce
```
res = db.table(table_name).update({"notes": notes}).eq("id", user_id).execute()
```
## Expected behavior

Update and return me the row.

## Actual behaviour

`{'data': {'message': 'Error in $: not enough input'}, 'status_code': 400}`

## System information

- Version of supabase-py: 0.0.2

**Comment by rphly** [comment]
Temporary workaround is to use .insert() with upsert=True

**Comment by fedden** [comment]
Yes noticing this too. Is upsert actually working or is it simply inserting a new row? From what I've noticed it's inserting new rows so would be helpful to get confirmation thats what you are seeing. Perhaps request headers/jwt is misconfigured somehow..

**Comment by rphly** [comment]
@fedden it updates the row when I use insert with upsert=true.

**Comment by remybroun** [comment]
It would be nice to have this documented somewhere. Without this issue there is no way to know how to update a row.

**Comment by J0** [comment]
Hey @remybroun @rphly,

We have tested this issue and it seems to work fine now.  We are closing this for now but please feel free to let us know if you're still facing any issues. 
![image](https://user-images.githubusercontent.com/8011761/139558552-488da81c-743a-4664-b9ab-b5dd485b0ec7.png)

Thanks!

**Comment by Krish-Nerkar** [comment]
> Hey @remybroun @rphly,
> 
> We have tested this issue and it seems to work fine now. We are closing this for now but please feel free to let us know if you're still facing any issues. ![image](https://user-images.githubusercontent.com/8011761/139558552-488da81c-743a-4664-b9ab-b5dd485b0ec7.png)
> 
> Thanks!

I am still facing the same issue :(

`res = supabase.table("Servers").update({
                    "Server_ID" : previous_data['data'][0]['Server_ID'],
                    "Server_Name" : previous_data['data'][0]['Server_Name'],
                    "Channel_ID" : previous_data['data'][0]['Channel_ID'],
                    "Categories" : previous_data['data'][0]['Categories'], 
                    "Links": previous_links
                }).execute()`

![image](https://user-images.githubusercontent.com/49949733/139632439-97d83268-c5df-41f7-b587-8444616a9790.png)

**Comment by dreinon** [comment]
Make sure to update your supabase version to the latest and tell us if you still face the issue please 😊

**Comment by mohnish7** [comment]
Hello @dreinon - I am running into the same issue again despite having the latest supabase version

**Comment by smandava98** [comment]
How is this closed? I am still facing the same issue

**Comment by smandava98** [comment]
I recently faced this issue. If anyone comes across this again this was how I solved it:
I was using supabase-py instead of supabase. Also I updated supabase to latest version (1.0.3 as of this date) and my python version was 3.10.10.

**Comment by Bobbyjsx** [comment]
@smandava98 how were you able to use supabase in a python project without using supabase-py ??

**Comment by alananisimov** [comment]
> @smandava98 how were you able to use supabase in a python project without using supabase-py ??

You can try pip install supabase and you will have no errors))))

**Comment by AkashC-goML** [comment]
if you are using supabase_py or supabase-py instead use supabase alone to create client 

it is working for me any more issues add a comment
