### ISSUE TITLE
Broken link on README.MD

### ISSUE THREAD

**Issue by stuartcw** [supabase-community/supabase-py#304]
**Describe the bug**

The link at the bottom of README.md to https://supabase.com/visualizing-supabase-data-using-metabase is broken.

**To Reproduce**
1. Click on the link to Visualizing Supabase using Metabase.

**Comment by anand2312** [comment]
That's odd, maybe @J0 will know what's up

**Comment by wellsilver** [comment]
I fixed it in my pr #309 along with other things

**Comment by J0** [comment]
Sorry - just seeing this - there was a recent migration on the frontend so a bunch of the links are broken - I've gone ahead and merged the PR. Thanks for flagging this!
