### ISSUE TITLE
error select with eq 

### ISSUE THREAD

**Issue by PLLX76** [supabase-community/supabase-py#321]
**error**
`postgrest.exceptions.APIError: {'code': 'PGRST104', 'details': 'Failed to parse [("id","Filters.EQ.88")]', 'hint': None, 'message': 'Unexpected param or filter missing operator'}`

**code**
```python
from supabase import create_client, Client
supabase: Client = create_client(url, key)

data = supabase.table("list_v2").select("*").eq("id",1).execute()

print(data.data)
```

 - OS: windows
- version : 0.7.1

**Comment by MindSetFPS** [comment]
I have the same error. I'm no postgres expert but, could It be related with the Filsters.EQ expression and the id being inside the same string?

**Comment by PLLX76** [comment]
I don't know

**Comment by PLLX76** [comment]
thank you man
