### ISSUE TITLE
How to join tables?

### ISSUE THREAD

**Issue by arinmirza** [supabase-community/supabase-py#337]
What I want to do is fairly simple but it just doesn't work!
I have two different tables and I want to join and filter them.

```js
const { data, error } = await supabase
  .from('some_table')
  .select('some_column, other_table(*)')
  .gte('other_table.other_column', 10)
```

These tables are of course connected via foreign key relationship in supabase.

However this gives me the error that `some_table` does not have the column `other_table.other_column`. 

There is also this `table(column)` syntax and `table!inner(column)` syntax which I am also not sure if they are ported. What's the status on these?

**Comment by anand2312** [comment]
Realize I'm a little late, but is this happening with the Python client? @arinmirza

**Comment by J0** [comment]
Going to close for now but feel free to re-open if there are still issues.

Thanks!

**Comment by ManuelLerchner** [comment]
I have exactly the same type of problem.

If I use a normal query, it returns the whole object, as expected.

```python
supabase.table("content").select(
            "id, stage(stage)").execute().data

>> [{'id': 'abc', 'stage': {'stage': '1'}}]
```

But as I start applying a filter, it throws a `column does not exist` error

```python
supabase.table("content").select(
            "id, stage(stage)").eq("stage.stage", "1").execute().data

>> postgrest.exceptions.APIError: {'code': '42703', 'details': None, 'hint': None, 'message': 'column content.stage.stage does not exist'}
```

Is this a bug, or am I just using the filter in a wrong way?

**Comment by tykimseoul** [comment]
I'm getting the same error as well.

Any ideas? 🤨

**Comment by ManuelLerchner** [comment]
In my case, the problem was that I used an outdated library version.

Just removing and then reinstalling the library via `pip` downloaded the newest version and the problem was solved.

**Comment by tykimseoul** [comment]
Oh, how have I not thought of that! 😂
I'm using 0.7.0 so I think that might be the reason. I'll give it a go.
Thanks for pointing it out! Appreciate it. 😀

**Comment by MoritzTema** [comment]
> There is also this `table(column)` syntax and `table!inner(column)` syntax which I am also not sure if they are ported. What's the status on these?

Just curious, are there any updates on this feature?
It's still mention in the [docs](https://supabase.com/docs/reference/python/select).

**Comment by J0** [comment]
@MoritzTema let me test and get back to you accordingly

**Comment by silentworks** [comment]
You can use `!inner` with this library. I have tested it and it works.
