### ISSUE TITLE
Update Documentation 

### ISSUE THREAD

**Issue by J0** [supabase-community/supabase-py#36]
# Improve documentation

Documentation as a whole is missing from the client library. It would be nice if we could furnish the [Sphinx Page] (https://supabase.readthedocs.io/en/develop/) with relevant documentation preferably from autodoc.

Currently this would mean documenting:
- [x] Auth
- [x] Storage
- [ ] QueryBuilder

**Comment by manavmodi22** [comment]
Hey @J0 I would like to work on this issue. How can I proceed further? Also is the issue part of Hacktoberfest 2021?(just curious)

**Comment by dreinon** [comment]
@manavmodi22  Yes! Any issue is part of Hacktoberfest 2021, since the whole library is participating. Feel free to go for it :smile: !

**Comment by siddhiiguptaa** [comment]
Hey @manavmodi22 I would like to know, are you working on all the pointers? If you wish and like it, maybe we could split up the task. Also would like to confirm from @darora is it possible to split up the task? 🤔

**Comment by manavmodi22** [comment]
hey @siddhiiguptaa feel free to work on the issue. I am not working on it, currently..

**Comment by J0** [comment]
Hey team, 

Yup as @dreinon has mentioned feel free to go for the issue. Everything here is part of hacktoberfest. You can take a look in the docs folder to get a rough idea of how to proceed. We use Sphinx for documentation.

**Comment by arshamg** [comment]
Are there any other open issues related to docs for supabase storage? Would love to contribute.

**Comment by J0** [comment]
Hey!

Docs wise there's a yaml file - https://github.com/supabase/supabase/blob/master/spec/supabase_py_v2.yml which  corresponds to the [docs section](https://supabase.com/docs/reference/python/v0/initializing) and describes most of the methods. I think not everything that's implemented is covered - if you're up for it you could enhance that. One example of undocumented library features would be [storage image transformations](https://supabase.com/docs/guides/storage/image-transformations)

Alternatively, if you'd be open to library contributions I think there's still a few methods like `upload` which don't support all use cases cleanly (e.g. file upload) or  don't support the full set of options that the js lib offers. 

Hope this helps in some way - lmk if there are questions

**Comment by arshamg** [comment]
Thanks! The yaml file looks like a great place to start :)

**Comment by J0** [comment]
Sounds good! Feel free to let me know if there's any way I can be helpful

**Comment by J0** [comment]
This should now be documented on the Supabase site and should be gradually updated as new bindings are released- https://supabase.com/docs/reference/python/introduction
