### ISSUE TITLE
Authentication Documentation Obsolete?

### ISSUE THREAD

**Issue by youcefjd** [supabase-community/supabase-py#365]
I am facing an issue with the sign_up/sign_in methods in Python for client.auth. Basically, I am following the documentation found on this repo, but I get the following error:

```
from supabase import create_client

url = "myURL"
key = "myKey"

email  = 'random@gmail.com'
password  = '12345'

user = supabase.auth.sign_up(email=email, password=password) 


```

The above code returns this: 
```
TypeError: SyncGoTrueClient.sign_up() got an unexpected keyword argument 'email'
```

I also tried 

```
user = supabase.auth.sign_up(email, password) 

```
But getting this:
```
AttributeError: 'str' object has no attribute 'get'
```
Thanks

**Comment by jbasko** [comment]
Yes, it looks like the documentation is obsolete now. I started trying this library just yesterday and I can't say it matches my expectations after a few weeks of experience with the JS client.

In your case, if you're on the just released 1.0.0, then you should be able to see `SyncGoTrueClient.sign_up` signature in your IDE. It shows that it accepts only a "typed" dictionary called `credentials` of "type" `SignUpWithPasswordCredentials` which is a `Union` of `SignUpWithEmailAndPasswordCredentials` and `SignUpWithPhoneAndPasswordCredentials`. In your case it is `SignUpWithEmailAndPasswordCredentials` which expects a dictionary with two mandatory keys `email` and `password`. In other words, you have to call:

```python
supabase.auth.sign_up({"email": email, "password": password})
```

**Comment by youcefjd** [comment]
Thanks! That works. I was looking at the datatype that was required, and since it needed to have a 'get' method, I assumed it was a dictionary, but I couldn't get the attributes right. Thanks for clarifying that up!

**Comment by jbasko** [comment]
Cool @J0 . Would love to see this library mature as I have decided to bet on Supabase. You already saw my comment on #367 -- that's my main concern so far. I am happy to contribute a little in the next 10 days an hour a day or so. jazeps.basko @ gmail.com

**Comment by J0** [comment]
Hey all,

We've added [a new version of the docs](https://supabase.com/docs/reference/python/) so am going to issue. We will continue iterating on the existing spec though.

@jbasko sorry about delay on this - if you're keen the doc reference could use some love - the file corresponding to the reference doc content is [here](https://github.com/supabase/supabase/blob/master/spec/supabase_py_v2.yml) 

Lmk if anyone has questions/issues

Jo
