### ISSUE TITLE
setting timeout parameter does not change timeout

### ISSUE THREAD

**Issue by mohnish7** [supabase-community/supabase-py#376]
**Describe the bug**
Despite setting a `timeout` parameter in clientOptions, the query still times out in 5 seconds

**To Reproduce**
```
from supabase import create_client, Client
from supabase.lib.client_options import ClientOptions

client_options = ClientOptions(timeout=60)
supabase = create_client(SUPABASE_URL, SUPABASE_ANON_KEY, options=client_options)
```

**Expected behavior**
The function should now time out after 60 seconds

**Screenshots**
<img width="259" alt="Screen Shot 2023-02-15 at 2 04 18 PM" src="https://user-images.githubusercontent.com/7302380/219127526-32ac6069-2c8e-449e-aa5f-a1df883c4abf.png">

**Additional context**
I am running Supabase version 1.0.0

**Comment by J0** [comment]
Hey @mohnish7,

The timeout param currently isn't being passed through - a [fix was made](https://github.com/supabase-community/supabase-py/pull/369) but hasn't been published. I'll release it sometime this weekend - feel free to bump if you need it sooner

**Comment by dschnabel** [comment]
As per my [comment](https://github.com/supabase-community/supabase-py/issues/293#issuecomment-1429464174) the fix didn't seem to work for me. Does it work for others?

**Comment by J0** [comment]
Hey @dschnabel,

Just seeing this- it’s currently being passed to the postgrest client which may be why the fix doesn’t work out.  I’ll see if  I can pass it into the Auth client as well.

**Comment by mohnish7** [comment]
Hey @J0 were you able to successfully release this fix last weekend?

**Comment by mohnish7** [comment]
Hey @J0 following up again!

**Comment by J0** [comment]
Hey @mohnish7,

Thanks for the tag, so sorry didn't realize I missed this - wasn't able to get around to it but it's on my todo list for this week

**Comment by rotemCyberillium** [comment]
Hey @J0 

I'm dealing with the the same problem..

**Comment by enjalot** [comment]
I'm also dealing with this issue

**Comment by jon-qualifai** [comment]
Hey @J0 Seeing the same issue with calling Supabase from Python and seeing timeouts. Any luck with this issue?

**Comment by kernelguardian** [comment]
This might work
`
opts = ClientOptions().replace(postgrest_client_timeout=60)
supabase: Client = create_client(url, key, options=opts)
`

**Comment by J0** [comment]
Hey team,
Apologies just seting  this again.  Thanks for bumping - I'll re-open the issue. Can I confirm the issue is on the `postgrest-py` client for all of y'all

**Comment by kernelguardian** [comment]
Hey @J0  I am not sure. The feature seems to be working fine for setting client options, maybe update the documentation if it's the intended way of setting client options. Thanks

**Comment by J0** [comment]
Hey all,

We've updated the documentation around options - https://supabase.com/docs/reference/python/initializing?example=with-timeout-option

 It should work now. Do y'all mind trying again and then letting us know if there are still issues?

Thanks

**Comment by kernelguardian** [comment]
@J0  haven't touched that project in a while, will update once I get a chance. 
@devstein check the previous comment -> https://github.com/supabase-community/supabase-py/issues/376#issuecomment-1702061376

**Comment by devstein** [comment]
@J0 @kernelguardian Thanks appears to be working for us now

**Comment by Satoshilab21** [comment]
Does anyone know if this error relates to this?

APIError: {'code': '57014', 'details': None, 'hint': None, 'message': 'canceling statement due to statement timeout'}

When apply the Client Options the "read timeout error" no longer occurs but I now receive the above error. 

I am executing this statement in python where col1 is just a long column of numbers (~5.5M)

supabase.table('data').select('col1').order('col1', desc=True).limit(1).execute()

**Comment by jtewright** [comment]
FYI: https://github.com/supabase-community/supabase-py/issues/487#issuecomment-1801716462

**Comment by silentworks** [comment]
The docs has been updated on the website to show the correct way of doing timeouts. https://supabase.com/docs/reference/python/initializing
