### ISSUE TITLE
Support update/upload in Supabase Storage

### ISSUE THREAD

**Issue by J0** [supabase-community/supabase-py#39]
Right now not all `.upload()` and `.update()` is not supported in Supabase Storage.  We should support this to bring the library closer to parity with the JS client.

**Comment by XbIK** [comment]
"upsert" property is hardcoded. Also it would be helpful if the contentType could also be changed

`    DEFAULT_FILE_OPTIONS = {
        "cacheControl": "3600",
        "contentType": "text/plain;charset=UTF-8",
        "upsert": "True",
    }`

**Comment by J0** [comment]
Yup, closed
