### ISSUE TITLE
Incorrect padding when setting session from URL encoded access_token

### ISSUE THREAD

**Issue by philmade** [supabase-community/supabase-py#395]
**Describe the bug**
I'm trying to handle the redirects for verify-user and password reset. I have grabbed the access_token and refresh_token from the URL, passed it to the function supabase.auth.set_session(access_token, refresh_token) and I immediately get an 'incorrect padding' error.

I can decode the tokens on jwt.io no problem so was confused on the issue. Anyway, GPT4 came up with a custom solution that actually worked:

error:
```
access_token = 'foo'
refresh_token = 'bar'
 session = supabase.auth.set_session(access_token, refresh_token)
 response = supabase.auth.update_user({"password": new_password}
```

Potential solution:
```
def custom_decode_jwt_payload(self, token: str):
    _, payload, _ = token.split(".")
    payload += "=" * (-len(payload) % 4)
    payload = base64.urlsafe_b64decode(payload)
    return json.loads(payload)
    
 SyncGoTrueClient._decode_jwt = custom_decode_jwt_payload
session = supabase.auth.set_session(access_token, refresh_token)
response = supabase.auth.update_user({"password": new_password})
```

**To Reproduce**
```
access_token = 'foo'
refresh_token = 'bar'
session = supabase.auth.set_session(access_token, refresh_token)
response = supabase.auth.update_user({"password": new_password})
```
**Expected behavior**
Expecting a session to be made but its erroring with incorrect_padding
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sangonzal** [comment]
I am also seeing this issue

**Comment by J0** [comment]
Hey,

Just tested and you should be able to call `set_session` with an `access_token` and `refresh_token` now w/o running into an error.  Let's track issues related to patching the session  retrievalon GoTrue #324 

Feel free to re-open if there are still issues though.

Thanks!
