### ISSUE TITLE
No Route matched with those values

### ISSUE THREAD

**Issue by YanSym** [supabase-community/supabase-py#401]
Hello,

I was running a Python script to retrieve data from the table, and suddenly it stopped working.
I am connecting using the supabase lib, and the API connection works fine, but when I try to get data from any tables, it says it cant find anything, altough the table does exist in the database.

I am simply using the command:
supabase.table("Users").select("*").execute()

And I get the same error message, for any table:
{'message': 'no Route matched with those values'}

Has anything changed in supabase at all?
All my tables are in the public schema.

Thank you very much.

**Comment by YanSym** [comment]
I realized the error, Supabase is blocking my IP address...why is this happening?

**Comment by J0** [comment]
Hey

This looks like a project specific issue - could you please [reach out to Supabase Support](https://supabase.com/support) if the issue persists? Thanks!

Going to close for now but feel free to ping/re-open if issue persists
