### ISSUE TITLE
Readtimeout

### ISSUE THREAD

**Issue by louis030195** [supabase-community/supabase-py#403]
**Describe the bug**

Select request timeout and timeout cannot be configured

Is there any way to configure the timeout?

**To Reproduce**

I don't know, unfortunately does not seem deterministic, scaling issue or something.

**Expected behavior**

Request execute most of the time properly at the same scale

**Additional context**

Linux, Cloud Run
pypi 1.0.2
FastAPI

Crashing here: https://github.com/different-ai/embedbase/blob/0478aeb949c07990fdefcde98b6894e6638df577/embedbase/database/supabase_db.py#L46

> Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi result = await app( # type: ignore[func-returns-value] File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__ return await self.app(scope, receive, send) File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__ await super().__call__(scope, receive, send) File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 333, in _sentry_patched_asgi_app return await middleware(scope, receive, send) File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/asgi.py", line 139, in _run_asgi3 return await self._run_app(scope, lambda: self.app(scope, receive, send)) File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/asgi.py", line 188, in _run_app raise exc from None File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/asgi.py", line 183, in _run_app return await callback() File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__ await self.middleware_stack(scope, receive, send) File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call return await old_call(app, scope, new_receive, new_send, **kwargs) File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__ raise exc File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__ await self.app(scope, receive, _send) File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call return await old_call(app, scope, new_receive, new_send, **kwargs) File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__ await self.simple_response(scope, receive, send, request_headers=headers) File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response await self.app(scope, receive, send) File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call return await old_call(app, scope, new_receive, new_send, **kwargs) File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 108, in __call__ response = await self.dispatch_func(request, call_next) File "/app/middlewares/auth_api_key/auth_api_key.py", line 182, in dispatch response = await call_next(request) File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next raise app_exc File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro await self.app(scope, receive_or_disconnect, send_no_error) File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 227, in _sentry_exceptionmiddleware_call await old_call(self, scope, receive, send) File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call return await old_call(app, scope, new_receive, new_send, **kwargs) File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__ raise exc File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__ await self.app(scope, receive, sender) File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call return await old_call(app, scope, new_receive, new_send, **kwargs) File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__ raise e File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__ await self.app(scope, receive, send) File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__ await route.handle(scope, receive, send) File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle await self.app(scope, receive, send) File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app response = await func(request) File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/fastapi.py", line 130, in _sentry_app return await old_app(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app raw_response = await run_endpoint_function( File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function return await dependant.call(**values) File "/app/embedbase/app.py", line 153, in add existing_documents = await batch_select( File "/app/embedbase/db_utils.py", line 36, in batch_select existing_documents = await asyncio.gather(*[_fetch(ids) for ids in hashes_to_fetch]) File "/app/embedbase/db_utils.py", line 34, in _fetch raise e File "/app/embedbase/db_utils.py", line 30, in _fetch return await vector_database.select( File "/app/embedbase/supabase_db.py", line 46, in select return req.execute().data File "/usr/local/lib/python3.10/site-packages/postgrest/_sync/request_builder.py", line 55, in execute r = self.session.request( File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 821, in request return self.send(request, auth=auth, follow_redirects=follow_redirects) File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 908, in send response = self._send_handling_auth( File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 936, in _send_handling_auth response = self._send_handling_redirects( File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 973, in _send_handling_redirects response = self._send_single_request(request) File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1009, in _send_single_request response = transport.handle_request(request) File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request with map_httpcore_exceptions(): File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__ self.gen.throw(typ, value, traceback) File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions raise mapped_exc(message) from exc httpx.ReadTimeout: The read operation timed out

**Comment by louis030195** [comment]
hmm, nevermind, see where the issue is

**Comment by omair-khalid** [comment]
@louis030195 could you please tell where the error was?
