### ISSUE TITLE
How can I execute a SQL command using supabase client?

### ISSUE THREAD

**Issue by joselitofilho** [supabase-community/supabase-py#417]
Hello,

I would like to execute a command using a supabase client instance. For example:

-- main.py
```python
from supabase import create_client, Client

supabase_url = os.getenv('NEXT_PUBLIC_SUPABASE_URL')
supabase_key = os.getenv('NEXT_PUBLIC_SUPABASE_ANON_KEY')

supabase_client: Client = create_client(supabase_url, supabase_key)
    
result = supabase_client.execute("select disable_all_rls();")
print(result)
```

or read the commands from a sql file:

-- commands.sql
```sql
INSERT INTO my_table (id, name, age)
VALUES
    (1, 'John', 25),
    (2, 'Jane', 30),
    (3, 'Bob', 45);
```

-- main.py
```python
from supabase import create_client, Client

supabase_url = os.getenv('NEXT_PUBLIC_SUPABASE_URL')
supabase_key = os.getenv('NEXT_PUBLIC_SUPABASE_ANON_KEY')

supabase_client: Client = create_client(supabase_url, supabase_key)
    
with open("commands.sql", "r") as file:
        commands = file.read()
        result = supabase_client.execute(commands)
        print(result)
```

It would be great to have this feature. Is there a way to achieve the functionality of the `execute` function for the supabase client using its existing functions?

Thank you.

**Comment by kunal-sharda** [comment]
Is this similar to the invoke functions command or am I missing something in your issue request?

**Comment by J0** [comment]
Hey,

This should be possible with the `rpc` call which we're fixing right now see #405 for details. You'd then define the rpc and call `.rpc('<name')` or similar.

the `invoke` function can also be used to call custom commands though it's usually intended for edge functions.

Thanks!

**Comment by silentworks** [comment]
If you need to execute SQL then you should use a dedicated Python SQL library and execute them there or use a `.rpc` call as stated by @J0.
