### ISSUE TITLE
X-Client-Info header

### ISSUE THREAD

**Issue by awalias** [supabase-community/supabase-py#42]
we're rolling out a header similar to Stripe's App-Data in all of the client libs so issues can be debugged more easily between the client and the backend

the javascript libs are done already: https://github.com/supabase/supabase-js/pull/238

the format is: `X-Client-Info: supabase-js/1.11.0`

for client libs that wrap others (like how supabase-js wraps gotrue-js) we allow the wrapper lib to **overwrite** the wrapped lib's header (given that we can infer the gotrue-js version based on which supabase-js was used to make the call)

any help with rolling this out here would be incredible

**Comment by dreinon** [comment]
May this issue be closed already?
