### ISSUE TITLE
Simplify functions URL scheme.

### ISSUE THREAD

**Issue by thorwebdev** [supabase-community/supabase-py#447]
We can simplify https://github.com/supabase-community/supabase-py/blob/develop/supabase/client.py#L67-L75 as all functions can now run on https://ref.supabase.co/functions/v1/function-name.

See supabase-js change here: https://github.com/supabase/supabase-js/pull/778/files

**Comment by anand2312** [comment]
Thanks for the issue, this has been fixed in #467
