### ISSUE TITLE
How to filter `IS NOT NULL`?

### ISSUE THREAD

**Issue by laubonghaudoi** [supabase-community/supabase-py#448]
I would like to filter rows with the `IS NOT NULL` keywords but there is no such feature in the Python library. The JavaScript library has a `.is()` function to do this https://supabase.com/docs/reference/javascript/is But this doesn't exist in the Python lib at the moment? How to do this filtering using the python library?

**Comment by laubonghaudoi** [comment]
Finally found that in https://github.com/supabase-community/postgrest-py/blob/master/postgrest/base_request_builder.py#L286 So it's actually `._is()`

**Comment by anand2312** [comment]
Yeah we had to name it that because `is` is a Python keyword. But now I realise that leading underscores refer to "private" members by convention in Python so we might wanna think of another alias.

**Comment by laubonghaudoi** [comment]
Can we put more documentations about these keywords? Currently there is no way to know these apis except looking into the source codes.

**Comment by anand2312** [comment]
@laubonghaudoi we have documentation for [postgrest-py](https://postgrest-py.readthedocs.io/) on readthedocs; the list of filter methods are [here](https://postgrest-py.readthedocs.io/en/latest/api/filters.html). But you're right, visibility for those docs is really bad

**Comment by laubonghaudoi** [comment]
I see, thanks for the pointer to [postgrest-py](https://postgrest-py.readthedocs.io/). I never knew this doc exists. I think there should be documentation on the official [python doc](https://supabase.com/docs/reference/python/introduction)

**Comment by typytypytypy** [comment]
I would so appreciate if you could put the final syntax you used to get IS NOT NULL, I can't seem to get it to work with .is_('column',<WHAT_GOES_HERE>)

**Comment by laubonghaudoi** [comment]
@typytypytypy 
```typescript
supabase.table("table_name").select("column_1, column_2").is_("column_1", "NULL").execute()
```
So this is actually filtering `IS NULL` rather than `IS NOT NULL` but it works for me.

**Comment by jkolyer** [comment]
Not sure why this is closed.  No doc I've seen describes how to do in python "is not null".  It appears to unsupported.
