### ISSUE TITLE
Storage python client issue

### ISSUE THREAD

**Issue by srini047** [supabase-community/supabase-py#452]
**Describe the bug**
I am trying to list all the buckets that are available in my project.

```python
storage = supabase.storage()
new_bucket = storage.list_buckets()
new_bucket
```

But I get a `TypeError`, see the screenshot below!

**Expected behavior**
This code should return a list of all the available buckets for a project.

**Screenshots**
<img width="649" alt="Screenshot 2023-05-31 at 5 46 28 PM" src="https://github.com/supabase-community/supabase-py/assets/81156510/976c7b99-ac31-411c-8751-a2b7cfeca5d4">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: 16.5

**Comment by pybanaszak** [comment]
I'm having the same issue.

**Comment by joscha0** [comment]
I also get the error: `TypeError: 'SupabaseStorageClient' object is not callable`

For the file upload I fixed it by using 
```python
  res = supabase.storage.from_('bucket').upload(destination, os.path.abspath(source))
```
instead of `supabase.storage().from_()`

Maybe the [docs](https://supabase.com/docs/reference/python/storage-from-upload) are just outdated?

**Comment by J0** [comment]
Closing this issue since the docs are outdated but feel free to re-open if there are still issues.

Thanks!
