### ISSUE TITLE
Mistake in readme file 

### ISSUE THREAD

**Issue by gabrielgranado** [supabase-community/supabase-py#453]
**Describe the bug**
A recent update to readme file included the line

`user = supabase.auth.supabase.auth.sign_in_with_password({ "email": random_email, "password": random_password })`

clearly, it should be
`user = supabase.auth.sign_in_with_password({ "email": random_email, "password": random_password })`

As long as we are talking about the documentation. I would suggest to include a disclosure to explain that RLS does not work even if you sign in with your credentials and point a link to the issue discussion - or better, also the solution for it:

`supabase.postgrest.auth(supabase.auth.get_session().access_token)`

As it is very simple, I would suggest the edit myself, but it seem i am not allowed to? I`m very new to this git / github world.

**Comment by anand2312** [comment]
Thanks for the issue @gabrielgranado
