### ISSUE TITLE
Is there a way to specify at which schema is the table you want to query?

### ISSUE THREAD

**Issue by Harry-Kouraklis** [supabase-community/supabase-py#465]
eg. I have both auth.users and public.users.
How do I specify that I want to query the one or the other?

**Comment by anand2312** [comment]
The `create_client` method has an `options` parameter. `options` is a `ClientOptions` object, so make one with [`schema`](https://github.com/supabase-community/supabase-py/blob/5c752443277de0a4a8dfd7d0d113f0d177efc81f/supabase/lib/client_options.py#L16) set to the schema you want, and then pass that to create_client.
```py
options = ClientOptions().replace(schema="auth")
client = create_client(url, key, options)
```
The default schema is `public`
