### ISSUE TITLE
Bump Httpx version to ^0.24

### ISSUE THREAD

**Issue by ogabrielluiz** [supabase-community/supabase-py#482]
**Is your feature request related to a problem? Please describe.**
Yes. I'm having issues installing other dependency (zep-python) with supabase because it requires httpx <0.24 and zep-python >0.24.

**Describe the solution you'd like**
Bump httpx version to >0.24

**Describe alternatives you've considered**
I considered not using zep-python for the time being.

**Additional context**
I'm a maintainer on LangFlow and I was planning on adding Zep to it in our next release. This would help us greatly.

Thanks for the awesome project.

**Comment by cachho** [comment]
I'm in the same boat, with embedchain. 

`requirements.txt`
```
Flask==2.1.3
Flask-Cors==3.0.8
requests==2.28.0
gunicorn==20.1.0
Flask-Caching==2.0.2 
redis==4.4.2
supabase==1.0.3
embedchain==0.0.26
```

```
#0 405.7 ERROR: Cannot install -r requirements.txt (line 7), httpx[brotli,http2,socks]==0.24.1 and supabase because these package versions have conflicting dependencies.
#0 405.7 
#0 405.7 The conflict is caused by:
#0 405.7     supabase 1.0.3 depends on httpx<0.24.0 and >=0.23.0
#0 405.7     gotrue 1.0.1 depends on httpx<0.24.0 and >=0.23.0
#0 405.7     postgrest 0.10.6 depends on httpx<0.24.0 and >=0.23.0
#0 405.7     storage3 0.5.2 depends on httpx<0.24 and >=0.23
#0 405.7     supafunc 0.2.2 depends on httpx<0.24.0 and >=0.23.0
#0 405.7     httpx[brotli,http2,socks] 0.24.1 depends on httpx 0.24.1 (from https://files.pythonhosted.org/packages/ec/91/e41f64f03d2a13aee7e8c819d82ee3aa7cdc484d18c0ae859742597d5aa0/httpx-0.24.1-py3-none-any.whl (from https://pypi.org/simple/httpx/) (requires-python:>=3.7))
#0 405.7 
#0 405.7 To fix this you could try to:
#0 405.7 1. loosen the range of package versions you've specified
#0 405.7 2. remove package versions to allow pip attempt to solve the dependency conflict
#0 405.7 
#0 405.7 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by adityaraute** [comment]
Any updates?

**Comment by loong** [comment]
httpx has been bumped!
https://github.com/supabase-community/supabase-py/pull/514/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R22

**Comment by J0** [comment]
Going to close for now but let us knkow if there are any further issues.

**Comment by cachho** [comment]
With `v1.0.4` I'm running into new problems because `gotrue v1.0.3` requires `Pydantic >=v2.1` which I have 3 conflicts with.
I tried manually downgrading `gotrue`, but then I get conflicts with `postgrest`, so I guess other than convincing 3 different packages to use the latest version of Pydantic, the last thing I can try is sticking with `supabase v1.0.3` and then manually bumping httpx. :(

**Comment by J0** [comment]
Would it help if we bump all 3 packages to v2.1? If you're facing the issue I'm sure others will run into a similar problems

**Comment by cachho** [comment]
> Would it help if we bump all 3 packages to v2.1? If you're facing the issue I'm sure others will run into a similar problems

I opened an issue with the main package, looks like they're tracking it: https://github.com/chroma-core/chroma/issues/893

**Comment by santiemanuel** [comment]
I'm using nicegui and now the httpx version is ^0.24.1 which makes it incompatible with supabase-py
