### ISSUE TITLE
add documentation for update and delete in the supabase docs

### ISSUE THREAD

**Issue by IanEvers** [supabase-community/supabase-py#486]
there is an insert and fetch example in the docs https://supabase.com/docs/reference/python/insert but there is no update nor delete. i think they should be added.

**Comment by AdamGEmerson** [comment]
I've generated an issue over on the official supabase repo regarding this.  If I get the okay from the team I'll go ahead and try to update the docs.

**Comment by anand2312** [comment]
Yeah the docs over at supabase.com is not managed in this repo

**Comment by silentworks** [comment]
This has been done.
