### ISSUE TITLE
Requesting for new feature to get columns diistinct value from the db.

### ISSUE THREAD

**Issue by Muktadirul** [supabase-community/supabase-py#488]
**Is your feature request related to a problem? Please describe.**
I have tried to get distinct value from a table. There is no feature to do that. Can we have this feature ?

**Describe the solution you'd like**
select('table_name').distinct('column name').execute() 
expecting some functionality like this.

**Describe alternatives you've considered**
I have considered to query on a view but we need to go to editor and need to create a view and then query on that.

**Additional context**

**Comment by anand2312** [comment]
I don't think I quite get it - can you tell what a similar SQL query would look like?
In general as this library is just wrapping around the API exposed by [postgrest](https://postgrest.org) if the feature isn't supported by postgrest there's nothing we can do about it.

**Comment by Muktadirul** [comment]
Well in other way If I ask a simple question is how can I get the distinct value from a column using supabase sdk except creating a view ?

**Comment by silentworks** [comment]
PostgREST doesn't support this and this library relies on PostgREST.
