### ISSUE TITLE
TypeError when using the negation filter `.not_()`

### ISSUE THREAD

**Issue by laubonghaudoi** [supabase-community/supabase-py#496]
I want to build a query that filters `column1 IS NOT NULL`, and here is my code:

```typescript
response = supabase.table("table").select("column1, column2").not_().is_("column1", "NULL").execute()
```
And I believe `.not_().is_()` is the correct way to filter `IS NOT NULL`, according to https://github.com/supabase-community/postgrest-py/blob/master/postgrest/base_request_builder.py#L212 But I got this error:
```
TypeError: 'SyncSelectRequestBuilder' object is not callable
```
If I remove the `.not_()` the query runs fine with no error. So how to filter with negation, exactly?

**Comment by anand2312** [comment]
.not_ is a property, you don't need to call it (remove the parentheses)
