### ISSUE TITLE
Cannot install in server

### ISSUE THREAD

**Issue by modsushi** [supabase-community/supabase-py#499]
**Cannot install on render.com server**
 Could not find a version that satisfies the requirement supabase==1.0.0 (from -r requirements.txt (line 12)) (from versions: 0.0.3, 0.1.1, 0.2.0, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.5.7, 0.5.8, 0.6.0, 0.7.1)

it's using python 3.7.1
pip version 20

**To Reproduce**
1. Go to render.com free tier
2. try to use supabase in python

**Comment by J0** [comment]
Hey @modsushi,

Thanks for the query. Python 3.7 is now EOL and we've dropped support for it. I've attempted to install with 3.10 and it seems to be fine. Going to close but feel free to re-open if issue persists.

Thanks!
