### ISSUE TITLE
Type Hints for Supabase-py

### ISSUE THREAD

**Issue by J0** [supabase-community/supabase-py#50]
It would be nice if we could get type hints on the library so that we can allow users to sanity check their code.

Thank you @dreinon for proposing this!

**Comment by SwarajBaral** [comment]
Hey @J0 can I work on this ?

**Comment by dreinon** [comment]
@SwarajBaral Sure 😄

**Comment by SwarajBaral** [comment]
Thank you @dreinon ,I will give it a go. Just a question before I begin. Should I add type hinting to a single file and create a PR first ? Just to check if I am going on the right path or not ?

**Comment by J0** [comment]
@dreinon beat me to it and yes, go for it!

If you'd like, you can add hints to a single file and then request a review before moving on to the rest of the files.

**Comment by SwarajBaral** [comment]
Thank you for the reply @J0. I am on it.

**Comment by anand2312** [comment]
I can help with this as well; @SwarajBaral wanna split work? 😄

**Comment by aantn** [comment]
This is just a recommendation, but Pydantic supports autogenerating Python models from OpenAPI specs: https://pydantic-docs.helpmanual.io/datamodel_code_generator/

Might help with this.

**Comment by aantn** [comment]
On second thought, I think I'm misinterpreting this issue :)

The pydantic code generation is useful if you want to add type hints for the user's tables in Supabase, not to add typehints to the Supabase codebase itself.

**Comment by J0** [comment]
@aantn , go for it! It would be great if you could post a link here once you're done so that we can link to it

@dreinon  Don't think we have docs yet :( There is an examples page but it is still WIP We can definitely link to tutorials once we have a docs page though

**Comment by dreinon** [comment]
@leynier @anand2312 feel free to take this issue and split the work if you want since we got no response from @SwarajBaral yet.

**Comment by joeriddles** [comment]
Many modules and functions in this code base look to already be using type hints (typed).

Here are the functions I see that are not typed (so far):

- [ ] `client.py`
  - [ ] `DEFAULT_OPTIONS`
  - [ ] `def storage...`
    - [ ] does not have an explicit return type.
  - [ ] `def table...`
    - [ ] does not have an explicit return type.
  - [ ] `def from_`
    - [ ] does not have an explicit return type.
  - [ ] `def rpc`
    - [ ] function arguments are not typed
    - [ ] does not have an explicit return type.
  - [ ] `async def _close_subscription`
    - [ ] function arguments are not typed
    - [ ] does not have an explicit return type.
  - [ ] `def get_subscriptions`
    - [ ] does not have an explicit return type.
  - [ ] `def create_client`
    - [ ] `**options` could use the same type hint as `DEFAULT_OPTIONS`

**Comment by joeriddles** [comment]
I've been manually looking at files for missing type hints. Trying to use `mypy` to do this automatically. Here are my results so far:

```
> mypy -p supabase
pyproject.toml: Only all lowercase booleans allowed (line 25 column 1 char 733)
supabase\request_builder.py:1: error: Cannot find implementation or library stub for module named "httpx"
supabase\request_builder.py:2: error: Cannot find implementation or library stub for module named "postgrest_py.request_builder"
supabase\lib\storage\storage_file_api.py:3: error: Cannot find implementation or library stub for module named "httpx"
supabase\lib\realtime_client.py:3: error: Cannot find implementation or library stub for module named "realtime_py.connection"
supabase\lib\realtime_client.py:4: error: Cannot find implementation or library stub for module named "realtime_py.transformers"
supabase\lib\query_builder.py:3: error: Cannot find implementation or library stub for module named "httpx"
supabase\lib\query_builder.py:5: error: Cannot find implementation or library stub for module named "postgrest_py.client"
supabase\lib\query_builder.py:6: error: Cannot find implementation or library stub for module named "postgrest_py.request_builder"
supabase\lib\auth_client.py:3: error: Cannot find implementation or library stub for module named "gotrue"
supabase\lib\storage\storage_bucket_api.py:8: error: Cannot find implementation or library stub for module named "httpx"
supabase\lib\storage\storage_bucket_api.py:109: error: Return value expected
supabase\client.py:3: error: Cannot find implementation or library stub for module named "postgrest_py"
supabase\client.py:3: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
supabase\client.py:51: error: "object" has no attribute "update"
supabase\client.py:56: error: Incompatible types in assignment (expression has type "object", variable has type "str")
supabase\client.py:62: error: Argument 3 to "_init_supabase_auth_client" of "Client" has incompatible type "**Dict[str, object]"; expected "bool"
supabase\client.py:62: error: Argument 3 to "_init_supabase_auth_client" of "Client" has incompatible type "**Dict[str, object]"; expected "Dict[str, Any]"
supabase\client.py:62: note: "Dict" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
supabase\client.py:62: note: Consider using "Mapping" instead, which is covariant in the value type
supabase\client.py:62: error: Argument 3 to "_init_supabase_auth_client" of "Client" has incompatible type "**Dict[str, object]"; expected "Dict[str, str]"
supabase\client.py:73: error: Argument 3 to "_init_postgrest_client" of "Client" has incompatible type "**Dict[str, object]"; expected "Dict[str, str]"
supabase\client.py:153: error: Missing positional argument "table_name" in call to "SupabaseRealtimeClient"
supabase\client.py:154: error: Argument 2 to "SupabaseRealtimeClient" has incompatible type "Dict[str, Dict[str, str]]"; expected "str"
Found 20 errors in 7 files (checked 12 source files)
```

**Comment by anand2312** [comment]
@joeriddles Thanks for compiling this list! Helps a lot 😄
