### ISSUE TITLE
Unwanted exception - SupabaseException: supabase_url is required

### ISSUE THREAD

**Issue by adityaraute** [supabase-community/supabase-py#502]
**Describe the bug**
I copied the 'Initializing' code snippet from Supabase Python docs.
Inserted my URL and API Key as requested. 
But I'm still facing an exception.

When trying out snippets from the docs, we should not face any unwanted exceptions.

**To Reproduce**
1. Go to 'https://supabase.com/docs/reference/python/initializing'
2. Click on 'copy' button in the code snippet and paste in your Python notebook
3. Fill in your URL and API Key in the snippet
<img width="1395" alt="image" src="https://github.com/supabase-community/supabase-py/assets/43912470/df91e87e-e1fe-44ae-8b69-ccaefb589226">

**Expected behavior**
No exceptions should appear when using code from the docs as it is. If any, then notes should be made in the docs itself.

**Screenshots**
Pasted above

**Desktop (please complete the following information):**
Colab notebook
pip install Supabase was run

**Comment by devilsaint99** [comment]
Hi @adityaraute, you should create a project by going to https://supabase.com/ you will be redirected to a page where you will get project url and key of your project which you have to use in your code. 
Alternatively if you have already created project you can go to settings of project and under API find both url and keys
FYR.
![image](https://github.com/supabase-community/supabase-py/assets/36355889/16935960-90fd-4da8-aeae-03c1cd0af242)

**Comment by J0** [comment]
Hey @adityaraute,

Thanks for the query! As @devilsaint99 mentioned you'll need to copy over the appropriate  supabase  URL key from settings > API

I've also tested it locally and there should be no exceptions thrown on the latest version. Do let me know if this is not the case for you though.

Thanks devilsaint99 for jumping in. Appreciate your detailed response!

Thanks!
