### ISSUE TITLE
The operation did not complete (write) (_ssl.c:2396)

### ISSUE THREAD

**Issue by Mansitos** [supabase-community/supabase-py#509]
I'm getting error 

**The operation did not complete (write) (_ssl.c:2396)** 

while loading embeddings through langhchain on supabase.

The function that get this error is:
`self.embeddings_db = SupabaseVectorStore.from_documents(self.docs, self.embeddings, client=supabase_client)`

specifically, the error is produced in row: `result = client.from_(table_name).insert(chunk).execute()`
from `supabase.py` file, function `_add_vectors()`

By changing `chunk_size` variable to a smaller value (it is hard-coded to 500) it fixes the problem.

Any suggestion? any way to change chunk_size?

![image](https://github.com/supabase-community/supabase-py/assets/36408034/36c20c2b-a54d-4cfa-be25-c2c9e2a7636a)

**Comment by J0** [comment]
Perhaps it might be timing out as we use `httpx` which has a built in timeout of 5s. Don't think the js client has a timeout - was going to suggest moving the vector store to `vecs` which is an official Supabase-py for embeddings and probably more performant for working with embeddings

Do you mind opening an issue about this on langchain instead? Feel free to tag me if needed

**Comment by silentworks** [comment]
Stale issue so closing this one out.
