### ISSUE TITLE
pydntic error on importing supabase

### ISSUE THREAD

**Issue by Saatvik-droid** [supabase-community/supabase-py#517]
**Describe the bug**
If I import supabase as `from supabase import create_client` it leads to an import error for field_validator from pydantic.

**To Reproduce**
1. Install supabase using conda.
2. Import supabase.

**Expected behavior**
Import with no errors.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: linux
 - Version 1.0.3

**Comment by OsmnShkh** [comment]
Also getting a Pydantic import error after installing Supabase.

**Comment by Rohianon** [comment]
@olirice, 

I think this is the same issue I was facing. 

I actually had installed a plethora of packages together and experienced this. 

Here is the code I used.
```
!pip install langchain --quiet
!pip install openai --quiet
!pip install pdf2image --quiet
!pip install tiktoken --quiet
!pip install unstructured --quiet
!pip install supabase --quiet
```

And the error on installation. 

![image](https://github.com/supabase-community/supabase-py/assets/41194018/31a20adb-5edd-496c-9e04-c24955b529ba)

**Comment by Saatvik-droid** [comment]
If I uninstall supabase and do a clean install of pydantic I can import field_vector without any errors.

**Comment by olirice** [comment]
Tracking at 
https://github.com/supabase-community/postgrest-py/issues/282

**Comment by olirice** [comment]
also here 
https://github.com/supabase-community/gotrue-py/issues/291

**Comment by J0** [comment]
Hey team,

Going to close since the corresponding PRs have been merged but feel free to re-open if there are still issues.

Thanks!

**Comment by JasonGross** [comment]
This issue is not fixed, supabase install works fine with pip but still does not work with conda.  I created a test repo to demonstrate the issue in a clean environment on GitHub actions: https://github.com/JasonGross/bug-testing/actions/runs/6285807455/job/17068569212
