### ISSUE TITLE
Need to access custom schemas through Client, or make them public via API or UI

### ISSUE THREAD

**Issue by yaminivibha** [supabase-community/supabase-py#518]
**Describe the bug**
All schemas cannot be accessed via ClientOptions
**To Reproduce**
1. Create a schema in supabase UI
2. Try to access that schema using supabase-py

**Expected behavior**
You will not be able to access any schema created in Supabase UI through the supabase-py client, even when specifying that schema in ClientOptions. 

There's no way of making a schema "exposed" or "public" in the [schema documentation on postgresql.org](https://www.postgresql.org/docs/current/sql-createschema.html) so it's not clear how schemas are meant to be exposed for usability by supabase-py client. 

**Code used**
I'm using the following code to connect to supabase-py and postgreSQL
```from supabase import create_client
from supabase.lib.client_options import ClientOptions
url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_API_KEY")
supabase: Client = create_client(url, key)
opts = ClientOptions().replace(schema="embeddings")
supabase: Client = create_client(url, key, options=opts)
```

Which yields me the following error: 
```
APIError: {'code': 'PGRST106', 'details': None, 'hint': None, 'message': 'The schema must be one of the following: public, storage, graphql_public, wingman, wiseman'}
```

In Supabase, I have many schemas, including embeddings: 
<img width="258" alt="Screenshot 2023-08-15 at 11 46 51 AM" src="https://github.com/supabase-community/supabase-py/assets/75443071/09725eb6-6528-4d10-afa2-f108076af06f">

I see in the definition for ClientOptions that it should be possible to change the schema. I wrote the code for creating a client with a specific schema according to [this issue.](https://github.com/supabase-community/supabase-py/issues/490) However, I have no idea how to expose a schema via Supabase or Postgres. it seems like schemas created on the Supabase UI default to private when they aren't in the `public` schema and are inaccessible via supabase-py. How are we supposed to access these via API?

**Information**
 - OS: macOS
 - Using PostgreSQL on Supabase
 - supabase-py version 1.82.2

**Additional context**

**Comment by devilsaint99** [comment]
Hello @yaminivibha we expose schema under settings -> API -> API Settings just add the schema you want to expose.

**Comment by J0** [comment]
Hey @devilsaint99,

Thanks for jumping in! Appreciate it :)

Hey @yaminivibha,

Thanks for the query! As mentioned, you'll probably need to expose the schema on the dashboard

<img width="973" alt="CleanShot 2023-09-16 at 00 58 25@2x" src="https://github.com/supabase-community/supabase-py/assets/8011761/684264cf-da64-4f0b-901c-ddbafe9c68f7">

Going to close for now but do let us know if there are still issues and we'll reopen.

Thanks!
