### ISSUE TITLE
Bulk Delete by array of UUID strings

### ISSUE THREAD

**Issue by levi-katarok** [supabase-community/supabase-py#525]
**Describe the bug**
Unable to delete using a .filter('in", array_of_ids)

**To Reproduce**
1. Create a supabase python client (mine is under)
`self.commons['supabase']`
2. Have an array of uuids represented as strings ex:
`vector_ids = ["aed10938-65db-4678-8438-cf7684eaefd7", "94a58004-7f19-4e79-b189-0824e55d4c8a"]`
4. First I tried         
 `self.commons['supabase'].table('brains_vectors').delete().filter('vector_id', "in", vector_ids).execute()`

The error: 
```
raise APIError(r.json())
postgrest.exceptions.APIError: {'code': 'PGRST100', 'details': 'unexpected "[" expecting "("', 'hint': None, 'message': '"failed to parse filter
```

5. Then I tried 
`self.commons['supabase'].table('brains_vectors').delete().filter('vector_id', "in", tuple(vector_ids)).filter('brain_id', 'eq', self.id).execute()`

The error: 
`postgrest.exceptions.APIError: {'code': '22P02', 'details': None, 'hint': None, 'message': 'invalid input syntax for type uuid: "\'6eafc10e-6e1d-44c6-9ba9-99f2044b30d0\'"'}`

I wasn't able to convert those strings to double quotes without python changing them to single quotes. 

**Expected behavior**
I was hoping to be able to bulk delete a bunch of vector ids for an LLM application. Right now it takes ~0.5 seconds per vector to delete in a for loop. For a 1MB file with 237 vectors, it feels like 2 mins in a long time. 

**Screenshots**.

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura
 - IDE: Visual Studio Code

**Additional context**
Supabase version: `supabase==1.0.3`

If anyone knows how to do this bulk delete any help is greatly appreciated. I'm happy to help makes the changes or add to documentation as well! 

Thanks!

**Comment by silentworks** [comment]
If you're using the `.filter` with `in` you need to convert the id's into a comma separated string format with open and close brackets `(5caadd74-0e93-4929-9311-5cfade01d208,835ebdab-a113-459e-b45e-7677381ab4aa)` or you can use the `.in_` method with an array as you have above.

https://github.com/supabase-community/supabase-py/assets/79497/6ec503ca-abc2-41fa-b497-d46a953e3744

**Comment by silentworks** [comment]
Closing this out as it's not an issue with the library from my tests.
