### ISSUE TITLE
install not possible because of version conflicts

### ISSUE THREAD

**Issue by digi604** [supabase-community/supabase-py#533]
**Describe the bug**
Trying to install this package with "poetry add supabase" gives the following error:

Because no versions of supabase match >1.0.4,<2.0.0
 and supabase (1.0.4) depends on postgrest (>=0.10.8,<0.11.0), supabase (>=1.0.4,<2.0.0) requires postgrest (>=0.10.8,<0.11.0).
Because postgrest (0.10.8) depends on pydantic (>=2.1.0,<3.0)
 and no versions of postgrest match >0.10.8,<0.11.0, postgrest (>=0.10.8,<0.11.0) requires pydantic (>=2.1.0,<3.0).
Thus, supabase (>=1.0.4,<2.0.0) requires pydantic (>=2.1.0,<3.0).
So, because main depends on both pydantic (^1.10.4) and supabase (^1.0.4), version solving failed.

**To Reproduce**
poetry add supabase

**Expected behavior**
It installs

**Desktop (please complete the following information):**
 - OS: osx

**Comment by sarperdag** [comment]
Having the same problem, this issue still persists.

**Comment by sarperdag** [comment]
Requiring pydantic higher than v2 conflicts with many other packages. A recent discussion is here. 

https://twitter.com/jeremyphoward/status/1703112053446385915

Is it possible to go pydantic 1.x ?
