### ISSUE TITLE
Delete all query

### ISSUE THREAD

**Issue by PLLX76** [supabase-community/supabase-py#534]
Hello, this is to know if it was possible to delete all the data in a table because it causes an error. My code :
```python
supabase.table("messages").delete().execute()
```
And my error
```
APIError: {'code': '21000', 'details': None, 'hint': None, 'message': 'DELETE requires a WHERE clause'}
```
thank you in advance for your response

**Comment by J0** [comment]
Hey!

We don't support this  both in the Python and the JS lib. It is allowed if you [directly query Postgres](https://postgrest.org/en/stable/integrations/pg-safeupdate.html#block-fulltable) but we recommend using filters.

The workaround is to use an `rpc` call (which we're fixing right now)

Going to close but let me know if there are further issues. Thanks!
