### ISSUE TITLE
Reset DB at current migration

### ISSUE THREAD

**Issue by Ben-Epstein** [supabase-community/supabase-py#538]
**Is your feature request related to a problem? Please describe.**
Currently, especially for testing, it is very slow to reset the database. I have to run `os.system("npx supabase db reset")` -- Whereas with postgres/using sqlalchemy, I can just drop all tables and recreate them.

**Describe the solution you'd like**
Via the python SDK, a command like `supabase.admin.reset()` that will drop all tables and recreate them fresh. Or similarly, `supabase.admin.drop_all()`, `supabase.admin.create_all()` that leverages the underlying postgres db. 

**Describe alternatives you've considered**
Migrating to using the underlying postgres connection myself with sqlalchemy, but that seems tedious at this point (unless i'm missing something obvious)

**Comment by J0** [comment]
Hey @Ben-Epstein,

Thanks for the query! I can see the use case but wondering if there are any reasons against using the Supabase CLI (e.g. `supabase db reset`) 

Would love to know so I can relay any relevant feedback to the CLI team.

Lmk!

**Comment by Ben-Epstein** [comment]
Hey @J0

The main use-case is that it's currently unfeasible to reset my database after every test, or even after every test module. `supabase db reset` is simply too slow unfortunately. 

In previous projects I've used postgres directly and resetting the database has negligible time (dropping and creating all tables). With supabase, the db reset takes more time than most tests combined. 

I've noticed that to use supabase at all in my tests, you need to stand up quite a lot as well. Perhaps that's why the reset command is so slow. That's out of scope for this ticket though, maybe I'll make a new one to start that discussion:)

For this, maybe there could be a new cli or just curl that could be added to more quickly drop and recreate all tables that leverages postgres under the hood?

Thanks!

**Comment by J0** [comment]
Hey @Ben-Epstein,

Thanks for taking the time to reply! Wanted to circle back - checked in with the CLI team and they mentioned a couple of suggestions:

1. `supabase@beta` has a few speed updates so do consider trying that
2. If this is still slow consider using `truncate` statements only to delete data.

If both don't work do let us know and we'll take a deeper look.

> I've noticed that to use supabase at all in my tests, you need to stand up quite a lot as well. Perhaps that's why the reset command is so slow. That's out of scope for this ticket though, maybe I'll make a new one to start that discussion:)

Would love to hear more whenever you're free!

**Comment by Ben-Epstein** [comment]
> If this is still slow consider using truncate statements only to delete data.

Okay that sounds good, I will try that, thanks!

> Would love to hear more whenever you're free!

Sure thing. When just using postgres as a db, it's really simple and fast to get it running as a part of unit tests. Just stand up the db and run migrations. 

But with supabase, since it has auth, the rest API, etc, you need to stand up the entire stack of images. Not a problem in prod, but for unit tests it takes a lot of time to pull all the images and get them running every time. 

I was curious if we could stand up the database only without the other components, but it didn't seem possible. In the docker compose definition, the images were all inter-dependent, so I couldn't get a subset of them running successfully. 

The goal being to require fewer components in order to get dependencies running for unit tests.

**Comment by silentworks** [comment]
I don't think this is a concern of this library. You can use the Supabase CLI for this also you don't need to do a teardown after each test, just use random test data with something like Faker and you can get good results. You can also run the CLI with flags to exclude certain services from the setup https://supabase.com/docs/reference/cli/supabase-start?example=supabase-start-without-studio
