### ISSUE TITLE
Using supabase to protect a flask API

### ISSUE THREAD

**Issue by jantznick** [supabase-community/supabase-py#546]
This is mostly a call for clarification on some features, but if this leads to it I'd be happy to put together a sample repo showing how this could work and supabase could use it on their site as an example. I feel like this is probably a pretty common use case for a python implementation.

**Is your feature request related to a problem? Please describe.**
I'm currently working on creating a flask API that I want to use supabase to manage users permissions to the API. In the past I've used something like PassportJS to handle this on the server side in NodeJS.

**Describe the solution you'd like**
Users would be able to login via a form on my website, then the flask server uses supabase to auth the user and add a cookie or some other session identifier to user requests, in future requests I can have a middleware verify the user is allowed to use any API endpoint with another call to supabase to get permissions based on the users session identifying cookie/whatever is being used.

**Describe alternatives you've considered**
I've not considered any alternatives but am open to them, this is just the workflow that is used across most PassportJS docs and seems to work well there. If there's a better solution I'd definitely go with that. I'm only starting out with flask and supabase so am sticking with what I know for now.

**Additional context**
Here's where my problem is, I'm largely unsure, what if any of my above workflow supabase should be currently supporting, or wants to support in the future. I have a very small sample repo here:
https://github.com/jantznick/supaflask/tree/main

This repo is attempting to mimic the above workflow, only instead of blocking a route it is printing out the user info. When running the flask app it works and allows user logins, however it seems to only be storing a single user in the supabase client on the server. Not doing anything with the client side requests coming in or going out. Is that what is supposed to happen or am I doing something wrong? When I login as one user it works fine, then I login as a different user in incognito, go back to the original tab and refresh and the new incognito user info is showing up in my python console.

This seems like it might be the way it's designed and how the library is supposed to function. In this case it would be up to me to add a cookie to flask requests and then when the request come through use a fetch user function based on this cookie? I believe I could just attach the JWT from supabase and use that for authing users in future as part of my middleware?

Another question, should I be doing anything to 'log out' this client on the end of every request so that it isn't stored in the client on the server and accidentally sent out to a request?

**Comment by silentworks** [comment]
Thanks for pinging @J0, I'm actually working on something along these lines as an example app to figure out what needs improving in the Python libraries. I'm however not using Flask as an API in my setup but as the full blown webserver that renders the pages like a traditional Django app would. But would really love to see what you are working on @jantznick and also any feedback on what you've hit stumbling blocks with would be great too.

**Comment by jantznick** [comment]
@silentworks yeah I can put together some sort of basic info on doing this. I found an unrelated bug that was stemming from the gotrue library that I made a PR for so it's fixed now. I will post here when I have something, hopefully just a few days.

**Comment by silentworks** [comment]
@jantznick you can checkout my demo repo https://github.com/silentworks/supabase-flask-demo/, there are some features that might not work at the moment as their are PRs open to fix them and I am waiting for a new release of the `supabase-py` library to be published with these changes.

**Comment by jantznick** [comment]
@silentworks You're example is way more fleshed out than mine. I have a login page and then a couple basic routes. Same method though using an auth function wrapper that then passes the supabase user data to the flask route handler. I then just attach the access token to the request as a cookie and logout the user on the server so the session doesn't persist.

I've set up some custom user creation functions in my supabase instance so I want to take this app, build it out to be more of an api versus rendering views like it is now and then write a blog about how to get it set up.

https://github.com/jantznick/supaflask

Maybe do something similar with FastAPI as well down the road.

**Comment by chvanboven** [comment]
@jantznick That example was very useful.  I have added some templates and extended the decorator since it seems useful to be able to use some templates in both logged-in and logged-out state.

[https://github.com/chvanboven/SupaAuthFlask](url)

It might be good to extend this further as per your suggestions.

**Comment by jantznick** [comment]
@chvanboven Awesome, I love it! Something felt off about my example when I was making it and this is what I was looking for! 

One additional issue I've had with my original implementation is the forced redirect if a user isn't logged in, I wanted to play around with it returning an unauthorized error as JSON so that it can truly be used for APIs only if a user wanted that.

**Comment by silentworks** [comment]
Closing this out as there are two examples provided here and I think the original request was met.
