### ISSUE TITLE
There doesn't seem to be a way to check the difference between null and 'null' in the is() filter

### ISSUE THREAD

**Issue by AdamGEmerson** [supabase-community/supabase-py#557]
**Describe the bug**

It seems that when using `.is()`, there is no way to query for string literals that say "null".

In the supabase js library, this is the given example for `is()`:

DB
```sql
create table
  countries (id int8 primary key, name text);

insert into
  countries (id, name)
values
  (1, 'null'),
  (2, null);
```

Query
```ts
const { data, error } = await supabase
  .from('countries')
  .select()
  .is('name', null)
```
Response
```json
{
  "data": [
    {
      "id": 1,
      "name": "null"
    }
  ],
  "status": 200,
  "statusText": "OK"
}
```

This behavior cannot be replicated in the python library because rather than substituting `None` for the js keyword `null`, the python library uses the string `'null'` to check for nullness in the database. 

Replicating this in the python library gives a different result, row 2.
```python
data, count = supabase.table('countries') \
  .select('*') \
  .is_('name', 'null') \
  .execute()
```

```
('data', [{'id': 2, 'name': None}])

```

**Comment by AdamGEmerson** [comment]
On second look, this might just be an issue with the JS documentation. I suppose the correct way to query for a string `"null"` would be using `.eq()` not `.is_()`. I'll try messing around with JS library to confirm.

**Comment by silentworks** [comment]
This functionality has been added to the library https://github.com/supabase-community/postgrest-py/pull/446
