### ISSUE TITLE
Current upload does not support inclusion of mime-type

### ISSUE THREAD

**Issue by J0** [supabase-community/supabase-py#57]
Our current upload/update methods do not include the mime-type. As such, when we upload photos to storage and download them again they don't render properly.

The current fix was proposed by John on the discord channel. We should integrate it in so that Users can download/use photos. 

```
    multipart_data = MultipartEncoder(
        fields={
            "file": (
                "party-parrot.gif",
                open("./out/party-parrot.gif", 'rb'),
                "image/gif"
            )
        })

    formHeaders = {
        "Content-Type": multipart_data.content_type,
    }

    headers = dict(supabase._get_auth_headers(), **formHeaders)
    response = requests.post(
        url=request_url,
        headers=headers,
        data=multipart_data,
    )
```

**Comment by julianolf** [comment]
Hi there.

I am looking for some projects to contribute during this year's Hacktoberfest and I stumbled upon this one.

Supabase is a very cool initiative and I'm willing to help. :)

I would like to know if this issue is still available/open to assignment. The description above mentioned someone, John, is he already working on it?

**Comment by J0** [comment]
Nope, not to my knowledge. Feel free to file a PR

**Comment by julianolf** [comment]
> This issue should be closed right?

It should indeed. But I believe that only the author or someone with admin privileges are able to close it.

Maybe @J0 can.

**Comment by J0** [comment]
Yup @julianolf,

We are closing for now but feel free to let us know if you still face any further issues.

Thanks!
