### ISSUE TITLE
Change the functions method inside of supabase-py to a property

### ISSUE THREAD

**Issue by silentworks** [supabase-community/supabase-py#576]
Currently the supabase-py library has a functions method but this should follow all the other services inside of the library and use a property instead.

To currently invoke a function your code looks like:
```python
supabase.functions().invoke()
```

This change will make this code look like:
```python
supabase.functions.invoke()
```

**Comment by anand2312** [comment]
This will be a breaking change and as we've made a 1.0 release we'd be looking at a major-version change for this (following semver). What do you think our approach should be - allow the `functions().invoke()` with a deprecation warning till a 2.0 release? @silentworks @J0

**Comment by J0** [comment]
> allow the functions().invoke() with a deprecation warning till a 2.0 release (while making functions.invoke() the recommended default)

Sounds good to me
