### ISSUE TITLE
Support set_auth(token) and or customisation of headers for storage

### ISSUE THREAD

**Issue by fquellec** [supabase-community/supabase-py#616]
**Is your feature request related to a problem? Please describe.**
I'm currently using Supabase in a FastAPI middleware, I want to use RLS for permissions management. 
When the user logs in via my `/login` endpoint, I authenticate them with Supabase and return the access token provided by Supabase.
In subsequent calls, I want to retrieve the Supabase session of the user with the previous access token in order to make RLS-protected calls. 

**Describe the solution you'd like**
It would be nice to have a function `set_auth(access_token)` on the client in order to change the permissions of the client according to the user making the request. 

**Describe alternatives you've considered**
There is a workaround when uploading files, we can set the bearer token manually: 
```
response = supabase.storage.from_("files").upload(
        f"{str(user_id)}/{str(file_id)}",
        file_content,
        file_options={"authorization": f"Bearer {token}"},
    )
```

But this is not possible when downloading or listing files.. 

**Additional context**

**Comment by fquellec** [comment]
I think this is related to: https://github.com/supabase-community/gotrue-py/issues/221
I understand now that we can use: 
```
supabase.auth.set_session(token, refresh_token)
supabase.auth._remove_session()
```
It's confusing to be forced to use the refresh_token, even if we don't want to refresh the access_token.

**Comment by Atticuszz** [comment]
do we create supabase client for every user？

**Comment by johndpope** [comment]
in the client - this seems to fix things - 

```python
   def set_auth(self, *, access_token: str) -> Session:
        """Overrides the JWT on the current client. The JWT will then be sent in
        all subsequent network requests.
```

**Comment by Atticuszz** [comment]
> I think this is related to: https://github.com/supabase-community/gotrue-py/issues/221
> I understand now that we can use: 
> ```
> supabase.auth.set_session(token, refresh_token)
> supabase.auth._remove_session()
> ```
> It's confusing to be forced to use the refresh_token, even if we don't want to refresh the access_token.
> 
> 

you can use access_token simply by   
`client.auth.get_user(jwt=rsp_user.session.access_token)` 

 ```
    async def test_retrieve_user(self):
        rps_super = await self.superuser_sign_in()
        assert rps_super.session.user is not None, "user is None"
        pre_user = await self.client.auth.get_user()
        rsp_user = await self.client.auth.sign_in_with_password(
            {"email": "1831768457@qq.com", "password": "Zz030327#"}
        )
        assert rsp_user.session.user is not None, "user is None"
        after_user = await self.client.auth.get_user(jwt=rsp_user.session.access_token)
        assert pre_user.user.id != after_user.user.id, "id is equal"
        assert (
            pre_user.user.email != after_user.user.email
        ), "after get_user email is  equal"

        assert (
            after_user.user.email == "1831768457@qq.com"
        ), "after get_user email is not equal"
        rps = await self.client.auth.get_session()
        assert (
            rps.user.email == "1831768457@qq.com"
        ), "after get_session email is not equal"
```
here with more [tests](https://github.com/Atticuszz/supabase-py-async/blob/main/tests/test_auth_client.py)
