### ISSUE TITLE
Need to access private schemas through Client

### ISSUE THREAD

**Issue by JohnDotOwl** [supabase-community/supabase-py#618]
**Describe the bug**
I'm currently using https://supabase.com/docs/reference/python/start , service api , the data is not from a user, i basically just need to add data into the database for users. I've also added private to Exposed schemas and don't know if that's the best idea, basically all my data live inside private schema but i've certain data from external source i need to add into this schema

```
client = TelegramClient('bot', api_id, api_hash).start(bot_token=bot_token)

opts = ClientOptions().replace(schema="private")
supabase: Client = create_client(url, key, options=opts)
postgrest.exceptions.APIError: {'code': '42501', 'details': None, 'hint': None, 'message': 'permission denied for schema private'}
```

How else can i access private schema?

**Comment by silentworks** [comment]
You will need to also tell the API to expose this schema and also give permission to postgrest. We have a guide here that covers this https://supabase.com/docs/guides/api/using-custom-schemas

**Comment by silentworks** [comment]
Closing this one out as I don't think this is an issue itself.
