### ISSUE TITLE
self.auth.get_session() should be await

### ISSUE THREAD

**Issue by Atticuszz** [supabase-community/supabase-py#623]
open the file 
supabase/_async/client.py
and  _get_token_header methond in Class client
![image](https://github.com/supabase-community/supabase-py/assets/119986792/6236e7ae-e57b-43fb-b763-fa027dbad433)
@silentworks @J0 #

**Comment by RahulDubey391** [comment]
Hi @Atticuszz , I would like to work on this issue.

**Comment by Atticuszz** [comment]
thanks bro🥰

**Comment by Atticuszz** [comment]
> Hi @Atticuszz , I would like to work on this issue. 

I also designed the asynchronous version myself by referring supabase-py and use it alone. Maybe my idea is not mature enough. But I hope my code repository can help you ̋(ˊ•͈ꇴ•͈ˋ)

**Comment by Atticuszz** [comment]
thanks bro🥰 Your code work is impressively efficient
