### ISSUE TITLE
getting 'cannot execute INSERT in a read-only transaction' for a SELECT statement

### ISSUE THREAD

**Issue by peterbarty** [supabase-community/supabase-py#625]
**Describe the bug**
Trying to execute a select statement on the database with the following command:

```
customer_id_results = supabase.table('customers').select('id').filter('email', 'eq', user_email).execute()
```

yields:

```
postgrest.exceptions.APIError: {'code': '25006', 'details': None, 'hint': None, 'message': 'cannot execute INSERT in a read-only transaction'}
```

**To Reproduce**
1. Create a stripe schema and table for customers, following [these guidelines](https://supabase.com/docs/guides/database/extensions/wrappers/stripe)
2. Create a supabase client
```
supabase_options = ClientOptions()
supabase_options.schema = "stripe"
supabase: Client = create_client(url, key, supabase_options)
```
3. query the customers table
```
customer_id_results = supabase.table('customers').select('id').filter('email', 'eq', user_email).execute()
```

**Expected behavior**
SELECT statements should not yield any INSERTs. Query should return rows from customer table

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser [e.g. chrome]

**Comment by peterbarty** [comment]
I've followed these [guidelines](https://supabase.com/docs/guides/api/using-custom-schemas) for accessing custom schemas as well

**Comment by peterbarty** [comment]
I have tested and this is true for both tables with and without data present

**Comment by peterbarty** [comment]
This doesn't happen for non-stripe schemas, be it custom or public

**Comment by StanGirard** [comment]
Same issue ! You have to upgrade the version of the extensions wrappers in supabase to 1.19

**Comment by silentworks** [comment]
Seems this was a wrapper issue. We will close this one out now, if the issue still persists please comment on this issue or open a new issue.

**Comment by Slyracoon23** [comment]
I am experiencing the same issue but using the Javascript SDK instead on my local enviroment

**Comment by Slyracoon23** [comment]
@peterbarty  how did you resolve the problem?

**Comment by yusifahmadov** [comment]
Any solution?
