### ISSUE TITLE
Tutorial Request: FastAPI

### ISSUE THREAD

**Issue by J0** [supabase-community/supabase-py#63]
There have been multiple requests for a FastAPI tutorial. For this task, we're looking for a tutorial or blogpost which showcases the use of `supabase` with FastAPI.

There are no restrictions on the type of tutorial and any number of people can take this issue up. This issue is open for creative exploration but feel free to tag/ping me if ideas are needed.

**Comment by leynier** [comment]
Currently, I use subapase (specifically gotrue) with FastAPI, what I do is use supabase for authentication from the client, the client when making requests to an API in FastAPI sends the access_token, and from the FastAPI API, it verifies that this access_token be valid using supabase.

That is why I am currently quite focused on improving the gotrue package 😅

**Comment by J0** [comment]
@leynier,

That's pretty cool! If you have an example somewhere we'd love to include it in this repo.

@robertsiipola I'll set up an examples folder right now -- feel free to include any examples there.

**Comment by andrashann** [comment]
@leynier This setup with a FastAPI backend is exactly what I would need to get started with my supabase project; I'd be really happy if you could share your code or a write-up. Coincidentally, I think that tutorial would help close #58 as well.

**Comment by cloudguruab** [comment]
@J0 Submitted a PR #148 for this Issue

**Comment by juwiragiye** [comment]
I saw someone's PR and it was merged for this issue. Can I still do it?

**Comment by karolzlot** [comment]
@juwiragiye I think you can, the current tutorial is fairly simple and can certainly be improved and extended.

**Comment by J0** [comment]
@juwiragiye yeah additional tutorials are always appreciated!

**Comment by J0** [comment]
Closing this PR as it seems stale. I plan on recording a FastAPI video tutorial tomorrow which should hopefully address some common questions.
