### ISSUE TITLE
How to setup magic link login or is verify_otp working? If yes, how?

### ISSUE THREAD

**Issue by sarperdag** [supabase-community/supabase-py#655]
I basically need to get the magic link or password reset mechanism working. The documentation is really weak and I can't figure out how it works. 

Are we supposed to use verify_otp after the magiclink is sent and we get the token? If so, what are the parameters to sign in the user with a magic link? Or a password reset link? 

Thanks!

**Comment by silentworks** [comment]
I'm writing a blog post on this at the moment and it should be published this week. I will link it here once it has been published.

**Comment by sarperdag** [comment]
Awesome! Looking forward to it.

**Comment by silentworks** [comment]
@Sahithiaele the user was asking in reference to the Supabase Python library, I'm not sure how your solution above fits in.

**Comment by sarperdag** [comment]
I'm using python and django on the backend. However, I can't figure out how to implement it with supabase-py. Hope @silentworks's blog post will enlighten me when it's complete.

**Comment by sarperdag** [comment]
Any news on the blog post about this @silentworks ?

**Comment by silentworks** [comment]
@sarperdag looks like the blog post isn't published as yet, but you can view it on the Vercel preview for now https://zone-www-dot-com-git-blog-magic-link-python-auth-supabase.vercel.app/blog/magic-link-python-flask-apps

**Comment by sarperdag** [comment]
Thanks, just started implementing this but I'm getting a "Error sending magic link" error. It worked for 3-4 requests but then stopped sending email. I'm using my own SMPT provider.

**Comment by sarperdag** [comment]
> Thanks, just started implementing this but I'm getting a "Error sending magic link" error. It worked for 3-4 requests but then stopped sending email. I'm using my own SMPT provider.
> 
> Also tried using different SMTP providers but didn't solve the issue.
> 
> What could be the problem?

Never mind, fixed this issue. It was something on my side.

**Comment by sarperdag** [comment]
Anyways, I've implemented the code mentioned in the blog post and I was able to login the user. However, how do I change the password of the user later on? Because I'm using supabase on the backend, I can't use 

`supabase.auth.updateUser({ password: new_password })`

because I don't have different auth sessions for different users. I implemented my own session mechanism. One idea is to do a rpc call to update the password manually but in this case, I don't know what kind of hashing mechanism supabase uses to update store the passwords. Therefore I'm stuck...

**Comment by silentworks** [comment]
You should be able to use `supabase.auth.update_user({ password: new_password })` as the user would be signed in after a password reset link is sent with `supabase.auth.reset_password_email(email=email)`. All of these concepts can be seen in my demo app https://github.com/silentworks/flask-notes, even though this is written in flask the concepts are the same in every Python framework.

**Comment by sarperdag** [comment]
Thanks. Implemented it without any issues. Closing this issue.
