### ISSUE TITLE
Fastapi & supabase curd template 🫶

### ISSUE THREAD

**Issue by Atticuszz** [supabase-community/supabase-py#665]
[template](https://github.com/Atticuszz/fastapi_supabase_template)
![image](https://github.com/supabase-community/supabase-py/assets/119986792/cb7616cc-6536-4ae2-8a57-025d392c5807)
enjoy the power of supabase&fastapi！

**Comment by silentworks** [comment]
This is probably best showcased on the Github discussions. https://github.com/orgs/supabase/discussions
