### ISSUE TITLE
Can't complete Signing flow with flask, can't retrieve refresh_token 

### ISSUE THREAD

**Issue by alfonsodev** [supabase-community/supabase-py#670]
I'm implementing a sign_in flow in Flask, here is a brief explanation of the the flow:  

- I do `sign_in_with_password` and store `result.session.access_token` in a cookie ( http only )
- then on the next request I can read the token from cookie and retrieve user_id 
        token = request.cookies.get("token")
        user = supabase.auth.get_user(jwt=token)
        user_id = user.user.model_dump().get("id") 
        // missing a way to get refresh token by user_id 
        supabase.auth.set_session(access_token=token, refresh_token= )
        

I'm assuming I need to perform the following query  

```sql
select token from auth.refresh_tokens where user_id = $1
  and revoked  = false
  order by created_at desc limit 1; 
```
Since refresh_table is on auth schema, I've tried creating new client using ClientOptions schema with value auth, but then I'll get the error that only certain schemas are allowed.  

I've tried performing the same query with psycopg2  but seems that the workspace/table does't exist which is weird but I guess is hidden from postgres user.  

Here a simplified version of the Fask code: 

```python
@app.route("/login")
def login():
    result = supabase.auth.sign_in_with_password({"email": email, "password": password})
    access_token = result.session.access_token if result.session else None
    response = make_response(render_template("index.html"))
    response.set_cookie("token", value=access_token, httponly=True)

    return response

@app.route("/profile")
def profile():
    token = request.cookies.get("token")
    if token:
        user = supabase.auth.get_user(jwt=token)
        user_id = user.user.model_dump().get("id")
        refresh_token = # get refresh token from ??????
        supabase.auth.set_session(access_token=token, refresh_token=refresh_token)
    else:
        print("no token")
    return render_template("index.html")
```   
How I'm supposed to retrieve user's refresh_token and set the session ? 
or I'm missing something ?

**Comment by silentworks** [comment]
You shouldn't be retrieving and setting the session manually yourself. You can create a session provider and pass that to the `create_client` then use that as your session storage and it should handle everything automatically for you. I have a flask example project here which makes use of this https://github.com/silentworks/flask-notes, you can take a look at https://github.com/silentworks/flask-notes/blob/main/app/flask_storage.py and https://github.com/silentworks/flask-notes/blob/main/app/supabase.py files to see how this is implemented.

**Comment by alfonsodev** [comment]
thanks @silentworks that's very useful, I've been reading source code and docs, and my understanding is from what I read in 
https://supabase.com/docs/guides/auth/sessions   

A session for Supabase means JWT + refresh_token, refresh session means to exchange refresh token for a new JWT, (done with /token endpoint of gotrue).   

By using Flask session storage, and session means both JWT and refresh token, does it mean is storing both in a cookie? that would be "bad", specially seems like Flask session are not secure by default ? https://blog.miguelgrinberg.com/post/how-secure-is-the-flask-user-session

I really appreciate your sharing your code, I'm just trying to asses how much production ready is this approach.

**Comment by alfonsodev** [comment]
After reading the discussion https://stackoverflow.com/questions/32084646/flask-session-extension-vs-default-session 
I think it's now clear, the cookies are encrypted using the app.secret_key string in __init__.py  and that makes it not as bad.  
An improvement would be using the Flas Session extension , that stores session on the server side, but then you need to maintain that storage, so my point was, if we already have the refresh_token in auth database, why can't we just access it to refresh it, and store client side the JWT and server side the secret ( which is already there )  in that way is secure and scales better.  

Thoughts?

**Comment by alfonsodev** [comment]
Closing actually getting the refres_token is not a problem, get get it from `supabase.auth.sign_in_with_password` here is more a problem wether you trust default flask session, or you invest more time setting up Flask Session extension maintaining a key value store, or perhaps I wonder a simple profile table that just stores latest refresh token in Supabase, which properly set row security level.
