### ISSUE TITLE
How to get a url of uploaded image to Supabase bucket?

### ISSUE THREAD

**Issue by James-NJCN** [supabase-community/supabase-py#671]
I tried to upload an image to my bucket in Supabase according to this Supabase-py example. The return is "ID" and "key". A url of uploaded image is needed. How to get it?

**Comment by silentworks** [comment]
This depends on if the bucket is public or not. If it is public you can use the  [`get_public_url`](https://supabase.com/docs/reference/python/storage-from-getpublicurl) method:
```
res = supabase.storage.from_('bucket_name').get_public_url('test/avatar1.jpg')
```

Otherwise you will need to [create a signed URL](https://supabase.com/docs/reference/python/storage-from-createsignedurl) 
```
res = supabase.storage.from_('bucket_name').create_signed_url(filepath, expiry_duration)
```

**Comment by James-NJCN** [comment]
Thank you!
Best Regards,
James




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "supabase-community/supabase-py"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月22日(星期一) 下午4:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [supabase-community/supabase-py] How to get a url of uploaded image to Supabase bucket? (Issue #671)





 
This depends on if the bucket is public or not. If it is public you can use the  get_public_url method:
 res = supabase.storage.from_('bucket_name').get_public_url('test/avatar1.jpg')  
Otherwise you will need to create a signed URL
 res = supabase.storage.from_('bucket_name').create_signed_url(filepath, expiry_duration)
