### ISSUE TITLE
Supabase py RLS having issues on a celery worker

### ISSUE THREAD

**Issue by vpgits** [supabase-community/supabase-py#672]
Hi everyone, 

This is my first time using supabase, and doing a project of my own at this scale. I have a supabase database with several tables with rls enabled. I have been using the  `supabase.auth.set_auth(access_token, refresh_token)` method to authenticate a user to do CRUD on the backend. However when I start my celery task queue for the first time, only for the first request the responses are all empty signing that somehow the authentication flow didnt work but I tried running `supabase.auth.get_session()` right after that to find out the session is authenticated. For some reason i cant really find out whats the reason behind this and when i use the service key api this issue isn't there since it bypasses rls.

**Comment by silentworks** [comment]
Hi @vpgits, I would need a reproducible example repository in order to check what is happening here. I have never used celery before, but there could just be a slight delay in it getting the auth tokens due to it being a task queue. But It would be best to create a reproducible example first.

**Comment by vpgits** [comment]
I tried to replicate the issue on a brand new project but I couldn't. Seems like it might be because of a dependency issue.
