### ISSUE TITLE
Even though the row is deleted, it still appears as if it exists (Python)

### ISSUE THREAD

**Issue by cenkerozkan** [supabase-community/supabase-py#673]
I'm not sure if this is a bug or not, but I'll try to explain it as best I can with screenshots.

With the API I developed with FastAPI, I first pull reviews from Tripadvisor, analyze them, and then send them to two interconnected tables called reviews and analysis on Supabase.
<img width="615" alt="Screenshot 2024-01-22 at 23 52 54" src="https://github.com/supabase-community/supabase-py/assets/68559468/7ecc8b50-a22a-4753-861b-5eff65d1706e">

When the tables are both empty, I can insert comments into the tables when I first post them.

<img width="1377" alt="Screenshot 2024-01-22 at 23 54 22" src="https://github.com/supabase-community/supabase-py/assets/68559468/fb027f58-944b-4adf-95cb-600204869244">

But then, when I delete the comments in both tables via supabase UI and try to insert the same comments again via the API, I encounter the following error:

<img width="886" alt="Screenshot 2024-01-22 at 23 56 31" src="https://github.com/supabase-community/supabase-py/assets/68559468/ec61026a-1f92-4933-a704-ee0e4a8d17c1">

Even though both tables are empty, when I want to insert the same comment again, it says that there is already a row with the same ID. What could be the reason for this?

**Comment by kuldeepdev407** [comment]
So basically you are saying that you have a 2 tables interconnected with primary key and when you deleted both the table form supabase UI you are unable to insert data from API. Can you provide example for your API endpoint i will try to replicate.

**Comment by silentworks** [comment]
Do you have any database triggers setup to create the data in the related table?

**Comment by silentworks** [comment]
Closing this as there hasn't been any update from the OP since my last comment.
