### ISSUE TITLE
Use provided `JWT` to make supabase client object logged with this `JWT`

### ISSUE THREAD

**Issue by karolzlot** [supabase-community/supabase-py#70]
**Is your feature request related to a problem? Please describe.**

I would like to have this feature:  `supabase.auth.setAuth(jwt);`

https://github.com/supabase/supabase/discussions/1094#discussioncomment-714633

Currently I think I can just use JWT in `create_client(url, key)` and effect will be the same? (I'm not sure)

**Describe the solution you'd like**
above

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by leynier** [comment]
I'm currently working on a PR to add dataclasses to the responses and synchronize the functionalities between gotrue-py and gotrue-js, that functionality that you mention is already in gotrue-js so I will add it to gotrue-py in the PR.

https://github.com/supabase-community/gotrue-py/pull/23

**Comment by leynier** [comment]
When I say, **"currently"**, it is literal 😅. Here you have a preview

```python
def set_auth(self, access_token: str) -> Session:
    """Overrides the JWT on the current client. The JWT will then be sent in
    all subsequent network requests.

    Parameters
    ----------
    access_token : str
        A JWT token

    Returns
    -------
    response : Session
        A logged-in session

    Raises
    ------
    error : ApiError
        If an error occurs
    """
    session = Session(
        access_token=access_token,
        token_type="bearer",
        user=None,
        expires_in=None,
        expires_at=None,
        refresh_token=None,
        provider_token=None,
    )
    if self.current_session:
        session.expires_in = self.current_session.expires_in
        session.expires_at = self.current_session.expires_at
        session.refresh_token = self.current_session.refresh_token
        session.provider_token = self.current_session.provider_token
    self._save_session(session)
    return session
```

**Comment by leynier** [comment]
If I'm not mistaken (because I'm familiar with `gotrue`, but not much with the other libraries) they don't do the same.

By the way, what you want to make in the 1st option is currently possible. Although I do not know if a new release has been published with that change.

```python
supabase_client = create_client(url, anon_key)
supabase_client.auth.set_auth(user_jwt_key)
```

https://github.com/supabase-community/gotrue-py/blob/9ba3192dbdccd2f02a4819b52dd6cf51095af7e7/gotrue/client.py#L162

**Comment by 0xDebabrata** [comment]
Hey, not sure if I'm doing anything wrong. But the following does not seem to work. 
```py
session = supabase.auth.sign_in(email=os.environ.get("EMAIL"), password=os.environ.get("PASS"))

supabase.auth.set_auth(access_token=session.access_token)

data = supabase.table("videos").select("*").execute()
print(len(data.data))
```
This prints 0 normally but if I create the supabase client with the secret key, it prints the total number of rows. The table has RLS enabled.

**Comment by Antony-Jia** [comment]
from supabase import create_client, Client
The Client has no functions called set_auth.
Is that right?
