### ISSUE TITLE
Update dependency of httpx to 0.26 or higher

### ISSUE THREAD

**Issue by deaddrunkspirit** [supabase-community/supabase-py#703]
**Is your feature request related to a problem? Please describe.**
The version window 0.24 >= v > 0.26 is causing the problems with other packages that are relied on httpx of versions >= 0.26 (in my case it was python-telegram-bot). However there were no breaking changes in 0.26 and 0.27.
Also it appears that postgrest uses even older version of httpx (0.16) which make it impossible to download the dependency using any new version of httpx in a project

**Describe the solution you'd like**
Please update the version of httpx dependency so that 0.26 version is in bound. Note that packages that this project rely on (storage3 and postgrest have the same issue)

**Comment by silentworks** [comment]
There are breaking changes in `0.26` hence why an update hasn't been done for some packages. If you take a look at the tests here https://github.com/supabase-community/postgrest-py/actions/runs/8066427959/job/22035174490?pr=369 you will notice that URL encoding has changed in this version hence breaking the test. I will need to investigate this more to see how this will affect user code before upgrading.

**Comment by bwmhamad** [comment]
Hello,

We're also facing this dependency issue with one of our other used libraries.
Would be nice if you guys can update httpx to support 0.26.
That would solve it for us as well.

Thank you

**Comment by bmosterd** [comment]
We are facing the same issues as mentioned in the previous posts about the https version support.

Just wondering if there's been any progress on this? My project's pretty tied up in this, and I'm looking for any updates or workarounds you might have come across.

Thanks a bunch for looking into this!

**Comment by kiranparakkalkalam** [comment]
`supabase.table(table_name).select('*').execute()`

This is failing with this error `*** RuntimeError: QueryParams are immutable since 0.18.0. Use `q = q.set(key, value)` to create an updated copy.`

This I guess is a downside of updating the httpx version. Any idea how to resolve this?

**Comment by silentworks** [comment]
I'm going to take a look at this during the week. I need to run a few tests first to make sure there aren't any other BC issues besides the one I mentioned above.

**Comment by silentworks** [comment]
@kiranparakkalkalam I'm not sure how this is related to the issue mentioned here. Can you elaborate more on what you did to get this error and how it's related please?

**Comment by Wamy-Dev** [comment]
0.26 would be nice so I could proxies

**Comment by bmosterd** [comment]
@silentworks , thanks for diving into this. I am curious, do you have an update on this matter?

**Comment by silentworks** [comment]
Sorry last week was very eventful on my side so I will be looking at this today.

**Comment by silentworks** [comment]
I've bumped the version in the individual packages except `auth-py` as there is currently an issue stopping the package from being published to PyPi. Once this has been resolved I will update the `supabase` package to use the latest dependencies and make a release.

**Comment by jjfantini** [comment]
thank you @silentworks, would love to use with `websockets >= 12.0`

**Comment by silentworks** [comment]
@jjfantini I've added that into the mix for the next release too. This should be out soon-ish.

**Comment by silentworks** [comment]
Version 2.4.1 was just released which should resolve this issue https://pypi.org/project/supabase/2.4.1/.
