### ISSUE TITLE
Storage download failing due to JSON decode

### ISSUE THREAD

**Issue by ddematheu** [supabase-community/supabase-py#721]
# Bug report

## Describe the bug

`download` method is throwing an exception when downloading a file.

## To Reproduce

Initialize supabase client and attempt to download a file using method:

```python

response = supabase.storage.from_(bucket_name).download(file_path)

response = supabase.storage.from_(bucket_name).list(path)

```

Throws Error: Expecting value: line 1 column 1 (char 0)

Trace:
Traceback (most recent call last):
  File "/app/supabase_utils/download_utils.py", line 39, in download_with_retry
    response = supabase.storage.from_(bucket_name).download(file_path)
  File "/usr/local/lib/python3.10/site-packages/storage3/_sync/file_api.py", line 339, in download
    response = self._request(
  File "/usr/local/lib/python3.10/site-packages/storage3/_sync/file_api.py", line 49, in _request
    {**response.json(), "statusCode": response.status_code}
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 761, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

## Expected behavior

File is downloaded if its available or 400 is returned if the file is not available.

## System information

- OS: Linux

## Additional context

Seeing error across version 2.3.6-2.4.0

**Comment by ddematheu** [comment]
We are seeing a 403 error thrown. Seems transient as making the same request again will work.

**Comment by ddematheu** [comment]
Example request: (removed some values for security purposes)

HTTP Request: GET https://[BASE SUPABASE URL]/storage/v1/object/[BUCKET]/[FOLDER]/[FILE] "HTTP/1.1 403 Forbidden"

**Comment by kiwicopple** [comment]
Hey @ddematheu, thanks for the report

> *Seems transient as making the same request again will work*

Is there a possibility of a race-condition where the user is not yet logged in when making a request? If you log (before) each request can you see that the headers include the authorization code?

(Did you make any changes to your own application before 1030 PT? We haven't made any changes this weekend, and we aren't seeing this across other customers)

**Comment by J0** [comment]
Hey @ddematheu,

Thanks for the query - we've are looking into the issue. It looks like [we might need to update the error handling](https://github.com/supabase-community/storage-py/blob/main/storage3/_async/file_api.py#L48)

If possible, can I trouble you for the code surrounding the section where the `.download()` is called? Would also be helpful to know if the bucket is currently protected and if you have a file or URL that we can replicate this with. 

Let us know!

**Comment by silentworks** [comment]
@ddematheu please check 0.7.3 which should fix the `NameError: name 'JSONDecodeError' is not defined` issue.

**Comment by J0** [comment]
Hey @ddematheu,

Apologies I think an import was missed which @silentworks has patched 🙏

Will send over an email from support channel in a bit
