### ISSUE TITLE
[DEP]: Add `websockets >=12.0 support`

### ISSUE THREAD

**Issue by jjfantini** [supabase-community/supabase-py#740]
# Feature request

There are quite a few packages that are using the newer versions of `websocket` which makes `supabase-py`  un-usable for a lot of projects where `websockets` are used.

## Describe the solution you'd like

An upgrade of the dependencies to support `websockets >= 12.0`. This dependency restrictions is from the `realtime` package, which depends on `(>=11.0,<12.0)`.

This can also be solved by updating the `realtime-py` package, which included support for `websockets >=12.0, < 13.0`

## Describe alternatives you've considered

Firebase

**Comment by jjfantini** [comment]
@silentworks

**Comment by silentworks** [comment]
Version 2.4.1 was just released which should resolve this issue https://pypi.org/project/supabase/2.4.1/.
