### ISSUE TITLE
Full text search in python

### ISSUE THREAD

**Issue by aaa3334** [supabase-community/supabase-py#753]
Hi!

I am wondering if there is a way to do the full text search as described here? https://supabase.com/docs/guides/database/full-text-search?language=js&example-view=sql

Note I am fine on creating the fts column in the table I am searching, just when I am trying to do the actual search.

Note I am trying to use this:
initial_query = initial_query.filter('fts', 'plfts', keyword_query)

Where the keyword_query is either one word or a few strung together by |

If I attempt the same query in the sql in supabase itself it works, but it doesnt work if I try and use .filter and I am not sure what else to use (eg textsearch does not exist on it).

How can I get this to work?

I have considered:

1) Perhaps there is a different way to format it so I get the actual results here that i have just missed
2) Perhaps there is a way to send the sql statement directly? (this is in python so all in the back end)

Unsure how to get this to work

Thanks in advance!

**Comment by silentworks** [comment]
You would perform a full text search using the `.text_search` method.

```py
client.table("movies").select("*").text_search("title", "'The Aveng'").execute()
```

**Comment by silentworks** [comment]
This has now been documented in the reference docs https://supabase.com/docs/reference/python/textsearch
