### ISSUE TITLE
Outdated Pydantic version

### ISSUE THREAD

**Issue by MacKlinkachorn** [supabase-community/supabase-py#757]
Hi! Our systems rely on newer version of Pydantic (2.x+). However, Supabase python-client requires Pydantic < 2.0. This cause dependency conflicts and prevent us from using the client. Please let us know if there's a fix or work around for this.

**Comment by silentworks** [comment]
I'm not sure why this isn't working for you as I've checked our dependency version constraints and you should be able to install Pydantic 2.x+. You can see our version constraint in our pyproject file https://github.com/supabase-community/auth-py/blob/main/pyproject.toml#L20

**Comment by silentworks** [comment]
Closing this one out as haven't heard back from OP.
