### ISSUE TITLE
Uploaded images are always 1.37 MB big and can't be opened

### ISSUE THREAD

**Issue by colodenn** [supabase-community/supabase-py#78]
`supabase.storage().StorageFileAPI(id_='watermarked').upload(f'{_id}/{username}-{imageid}', os.path.dirname(os.path.abspath("__file__")) + "/embedded.jpg", {'Content-type':"image/jpg"})`

The file I'm trying to upload has a size of ~530KB. 
But on supabase it shows 1.37MB and can't be opened.

**Comment by Phillackinger** [comment]
Hi @colodenn, I have the same issue, but spotted a potential problem in your code: 

[In the docs](https://supabase.io/docs/reference/javascript/storage-from-upload) they specify the `Content-type` key as `contentType`.

**Comment by Phillackinger** [comment]
When I want to Upload an Image to a Supabase Bucket the MIME-Type is always: `application/x-www-form-urlencoded`

![grafik](https://user-images.githubusercontent.com/40075339/141958633-623d76aa-ca25-433f-8f05-0f4538fd707d.png)

My Code for the file upload looks like this

```python
files = supabase.storage().StorageFileAPI('files')
			//                              |           relative/path           |      C:/path/file      |       
			result = files.upload('img/' + values['ID'] + '.jpg', values['IMG_URL'], file_options={
				'cacheControl': '3600',
				'contentType': 'image/jpg',
				'upsert': False
			})
```
The Upload always returns a HTTP-Status Code 200 but the files are all broken when I download them. In XML files the `<` `>` are replaced with `%`
Maybe it's just my `file_options`

**Comment by kk21** [comment]
In storage_file_api.py > upload()
```
headers = dict(self.headers, **file_options)
headers.update(self.DEFAULT_FILE_OPTIONS)
```

I think the default file options shld be "switched":
```
headers = dict(self.headers, **self.DEFAULT_FILE_OPTIONS)
headers.update(file_options)
```

**Comment by leynier** [comment]
> In storage_file_api.py > upload()
> 
> ```
> headers = dict(self.headers, **file_options)
> headers.update(self.DEFAULT_FILE_OPTIONS)
> ```
> 
> I think the default file options shld be "switched":
> 
> ```
> headers = dict(self.headers, **self.DEFAULT_FILE_OPTIONS)
> headers.update(file_options)
> ```
> 
> I see that the current code in the repo is correct but my local code from pip install supabase isnt.
> 
> @dreinon Can you pls tell me how to get the latest code installed using pip install? Thanks.

`pip install git+https://github.com/supabase-community/supabase-py.git@develop`

**Comment by kk21** [comment]
Thanks @leynier . The upload now works.

However the header "cacheControl" cant be set and is always saved as "no-cache" in supabase storage.objects instead of "max-age=NumberSeconds".

**Comment by Phillackinger** [comment]
Thanks @leynier @kk21! 
It works for me as well now with the newest dev-version of the library.

**Comment by anand2312** [comment]
Closing as the issue seems to be fixed. Feel free to re-open if this is not the case.
