### ISSUE TITLE
Cannot chain multiple ilike or filter with ilike

### ISSUE THREAD

**Issue by harshdeep-techstax** [supabase-community/supabase-py#789]
Unable to chain multiple ilike like this

`supabase.table("products").select("*", count='exact').filter("name","ilike",f"%KitKat%").filter("category","ilike",f"%Candy Bar%").order(sort).limit(limit).execute()`

Getting error like
![image](https://github.com/supabase-community/supabase-py/assets/85677896/594d0354-e426-413b-8e1e-b18e2ff3d081)

**Comment by harshdeep-techstax** [comment]
Still getting the same error on single ilike as well
![image](https://github.com/supabase-community/supabase-py/assets/85677896/7fe022ee-d07a-4d92-b396-f30a2b01aa14)

**Comment by silentworks** [comment]
Please check if your project is paused in the Supabase dashboard.

**Comment by FBosler** [comment]
I am also getting those requests when using any kind of filtering, like:
- `ilike`
- `like`
- `filter`

One operation that works is `eq`. Using version 2.4.5

**Comment by regtm** [comment]
Also receiving these errors as soon as i use % in ilike. If i drop them the query executes fine.

**Comment by harshdeep-techstax** [comment]
> The % in the built query is causing your error, as the % is used for url encoding. Use * instead.

Yeah adding `*` instead of `%` worked.

**Comment by harshdeep-techstax** [comment]
@silentworks can you try chaining multiple ilikes as single ilike is working. I said multiple ilike chaining
for example select().ilike("title","%Home%").ilike("description","%father%").

It is now working when I replace % with *

**Comment by silentworks** [comment]
@harshdeep-techstax Its the same results for me with either single of multiple chaining ilikes.

https://github.com/supabase-community/supabase-py/assets/79497/2f1c360e-15ba-4f90-abe6-ee41021a82f4

**Comment by silentworks** [comment]
Closing as this is no longer an issue as demonstrated by the video in the previous comment.

**Comment by nosnatef** [comment]
Having the same problem, looks like the fix works
