### ISSUE TITLE
Errors on insert and update in certain situations

### ISSUE THREAD

**Issue by miyayuu123** [supabase-community/supabase-py#791]
Hello, I am experiencing irregular errors in a Python project using Supabase and would appreciate your advice.

Summary of the problem
When using the Supabase client to update the database and insert data, the process is successful at the start, but after multiple processes, when the same code is executed, an error occurs. The content of the code has not changed, only the position at which it is executed is different.

Error Details

Expecting value: line 1 column 1 (char 0)

At the start of processing, I can update the status of the models table and insert a new record in the results table.
However, if the same update and insert code is executed after multiple operations, an error will occur.

Code Abstraction Explanation
As shown in the following code snippet, we are using the Supabase client to perform database operations.

update_response = supabase.table("models").update({"status": "finished"}).eq("model_id", model_id).execute()
insert_response = supabase.table("results").insert({"model_id": model_id, "result": ""}).execute()

Tried Solution.
Checked error messages and status codes and logged API responses in detail.
Rechecked that environment variables were set correctly.
Checked transaction management and connection status.

Question
Are there any recommended troubleshooting steps in this situation? Also, any advice on a general approach to resolving this issue?
Any small tips are welcome. Best regards.

**Comment by silentworks** [comment]
I cannot recreate the issue from the code provided. It's best to create a reproducible github repo with the issue so we can investigate this further.

**Comment by silentworks** [comment]
Closing this out as there has been no reply in over a month.

**Comment by junaidlodhi22** [comment]
experiencing same issue. data getting posted to Supabase table. but it is raising exception
