### ISSUE TITLE
When using asynchronous client(acreate_client) error "detail": "'coroutine' object has no attribute 'auth'"

### ISSUE THREAD

**Issue by Bradkibs** [supabase-community/supabase-py#801]
# Bug report

## Describe the bug
when you create the client with acreate_client and use async functions that awaits for the supabase.auth.signin(credentials) you get the error above

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by silentworks** [comment]
This isn't a valid bug report. Please fill in the correct details and I will reopen this.
