### ISSUE TITLE
Unify HTTP Client to be httpx

### ISSUE THREAD

**Issue by dreinon** [supabase-community/supabase-py#82]
As mentioned in [this conversation](https://github.com/supabase-community/gotrue-py/pull/23/files#r744137183), `requests` module should be switched to unify `httpx` module as the HTTP Client for all Supabase Python libs.
@leynier Could you do this?

**Comment by leynier** [comment]
> As mentioned in [this conversation](https://github.com/supabase-community/gotrue-py/pull/23/files#r744137183), `requests` module should be switched to unify `httpx` module as the HTTP Client for all Supabase Python libs. @leynier Could you do this?

Ok, I will do it 👍🏼
