### ISSUE TITLE
Percentage wildcard in like filter throws `postgrest.exceptions.APIError`

### ISSUE THREAD

**Issue by fschay** [supabase-community/supabase-py#830]
# Bug report

## Describe the bug

I use the like filter as described in the documentation. I get the following error `postgrest.exceptions.APIError: {'message': 'JSON could not be generated', 'code': 500, 'hint': 'Refer to full message for details', 'details': ...`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```python
meeting_id = f'%{85770204020}%'
m = supabase.table('meeting').select('*').like('meeting_url', meeting_id).execute()
```
The meeting_url contains the meeting url with the meeting_id contained in the string.

## Expected behavior

Should return the database entries,  not throw an error. It seems for me an encoding error since if I replace the `%` with `%25` no error is thrown.

## System information

- OS: mac
- Version of supabase-py: supabase==2.5.1

**Comment by sulavpanthi** [comment]
Hello fschay, I noticed a subtle issue in your query pattern syntax.

The pattern should not include {} braces around the value. Instead, directly use % symbols around the value to match any string containing 85770204020.

Here's the corrected code:

`
meeting_id = '%85770204020%'  # Correct pattern syntax
m = supabase.table('meeting').select('*').like('meeting_url', meeting_id).execute()
`

This should resolve the issue. For reference, you can also check the example from the Supabase documentation [here](https://supabase.com/docs/reference/python/like).

If you have any further questions or issues, feel free to ask!

**Comment by fschay** [comment]
Ok thanks my bad.
