### ISSUE TITLE
Supabase CRUD operations not working

### ISSUE THREAD

**Issue by victorverma3** [supabase-community/supabase-py#864]
# Bug report

## Describe the bug
I am unable to perform fetch or upsert operations on my database table, despite successfully connecting to the Supabase client. I haven't tried any other operations because they are not needed for my use case. Interestingly, my Flask app is deployed on Render with a requirement of Supabase 2.5.1 and continues to work without a problem, but when I run it on my local machine, it doesn't work.

## To Reproduce

![Screenshot 2024-07-20 at 11 29 22 PM](https://github.com/user-attachments/assets/a2363da3-d591-40cb-ae50-48a435075644)

## Expected behavior

I expect a normal response to a fetch or upsert request, as documented in the supabase Python documentation.

## Screenshots

Error message:

![Screenshot 2024-07-20 at 11 32 20 PM](https://github.com/user-attachments/assets/3b6deea6-6d06-4e67-92cb-0b6510b25812)

## System information

`macOS`
`Python 3.10.7`
In my requirements.txt:
`aiohttp==3.9.5`
`beautifulsoup4==4.11.2`
`Flask[async]==3.0.3`
`Flask_Cors==4.0.0`
`matplotlib==3.8.4`
`numpy==2.0.0`
`pandas==2.2.2`
`python-dotenv==1.0.1`
`scikit_learn==1.4.2`
`seaborn==0.13.2`
`supabase==2.5.1` (also doesn't work in 2.5.3 fyi)
`xgboost==2.1.0`

## Additional context

Based on the error message, I decided to inspect the supabase source files on my machine. I found that the error is caused in the file `./supabase/_sync/client.py`:

![Screenshot 2024-07-20 at 11 38 42 PM](https://github.com/user-attachments/assets/d82c103b-1036-4a8f-b18f-af5b1368ad8c)

If I delete the `verify` parameter (which is defaulted to true) from the `_init_postgrest_client` function, and remove it as a keyword argument to `SyncPostgrestClient`, the error is resolved and my fetch and upsert work as expected. It would be great if someone more knowledge with the source code can look into this and figure out why this is happening on my end; I can't find anyone else having this error online.

**Comment by silentworks** [comment]
Can't replicate this, you should check that your dependencies are installed correctly. I've tested this with both `2.5.1` and the latest `2.5.3` without any issues. I've attached a screen recording showing this.

https://github.com/user-attachments/assets/1c69423b-7582-4664-9a25-c9b9b1a683c9

**Comment by victorverma3** [comment]
I manually deleted the supabase and postgrest dependency folders from my machine and then reinstalled both packages, and it works fine now. Not sure what caused the original problem but I should've tried this sooner. Thank you!
