### ISSUE TITLE
Delete from database, fails in response

### ISSUE THREAD

**Issue by KristofferE** [supabase-community/supabase-py#88]
**Describe the bug**
In query_builder.py at line 33 in return, response.json() fails with JSONDecodeError when api returns response.content as empty. 

**To Reproduce**
Delete object from supabase database:
```python
client.delete().eq("some id", some_id).execute()
```
Object is successfully deleted, but response message is not able to convert to json at throws exception.

**Expected behavior**
Deletion of object, and a response message telling me it was successfully, or an empty one. 

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Google Chrome
 - Version 96.0.4664.45 (Official Build) (arm64)

**Comment by leynier** [comment]
Sorry for the delay in responding, you could test that with the latest commit in develop.

**Comment by aantn** [comment]
This seems similar to https://github.com/supabase-community/supabase-py/pull/75/files

Are there plans to do a supabase_py release anytime soon? The above PR was fixed some time ago, but still hasn't been released.

**Comment by songololo** [comment]
Another running into this issue.

**Comment by dreinon** [comment]
A release is coming asap, before new year's eve 😄

**Comment by J0** [comment]
@dreinon @songololo @leynier  @aantn closing since it should be fixed with the latest release.

Let me know if anyone still has issues.

Thanks!
