### ISSUE TITLE
Could not find a version that satisfies the requirement supabase (from versions: none)

### ISSUE THREAD

**Issue by pvbhanuteja** [supabase-community/supabase-py#9]
Can't install python client for superbase

Could not find a version that satisfies the requirement superbase (from versions: none)

pip install supabase

**Comment by pvbhanuteja** [comment]
@J0

**Comment by pvbhanuteja** [comment]
@awalias @J0 @fedden @awalias 

Any update on this stuck for 3 days as the pip installation was failing.

**Comment by fedden** [comment]
Hi @pvbhanuteja if urgent please install locally after cloning develop branch

**Comment by fedden** [comment]
Will get around to a release via pypi soon

**Comment by pvbhanuteja** [comment]
Hi @fedden thanks for that, there is at least some progress in building up my logic.

I got caught with another issue cant update the record opened a new issue 
AttributeError: 'RequestBuilder' object has no attribute 'eq'

**Comment by J0** [comment]
Hey @pvbhanuteja,

@dreinon and I have just tested and we should now be able to install with `pip install supabase` we are closing this issue now but let us know if you face any further problems.
