### ISSUE TITLE
The "contains" query filter passes verbatim string "values" to Supabase in place of actual values.

### ISSUE THREAD

**Issue by aicushman** [supabase-community/supabase-py#93]
**Describe the bug**
The "contains" filter appears to incorrectly pass the verbatim string "values" to Supabase, in place of the intended query values.

**To Reproduce**
1. Create a Supabase client connected to a schema with table "table_name" having the JSONB column "column_name".
2. Invoke the "contains" filter with `supabase.table('table_name').select('*').cs('column_name','["value_name"]').execute()` 
3. See the error: `{'data': {'message': 'invalid input syntax for type json', 'code': '22P02', 'hint': None, 'details': 'Token "values" is invalid.'}, 'status_code': 400}`

**Expected behavior**
This should return any rows from "table_name" where the JSONB entry in "column_name" contains the value "value_name".

**Comment by leynier** [comment]
I think that this bug is from [postgrest-py](https://github.com/supabase-community/postgrest-py) and it was resolved at this https://github.com/supabase-community/postgrest-py/pull/37, only the dependency needs to be updated, which will be done soon. Greetings.

**Comment by rphly** [comment]
Bumping this :)

**Comment by dreinon** [comment]
Hi! This should be solved by now, so I'm closing this issue. Nevertheless, feel free to reopen it or comment again here if you have any more concerns. Thanks! 🙂
