### ISSUE TITLE
Add `MAINTAINERS.md`

### ISSUE THREAD

**Issue by joeriddles** [supabase-community/supabase-py#99]
**Is your feature request related to a problem? Please describe.**
It is unclear to me who maintains this project and who is a required reviewer on pull requests.

**Describe the solution you'd like**
I would like a `MAINTAINERS.md` file at the root of the repository that lists the project maintainers. In either this file or in `CONTRIBUTING.md`, I would like additional information to understand the review process for PRs.

Examples of `MAINTAINERS.md`:
- https://chromium.googlesource.com/external/github.com/grpc/grpc-go/+/refs/heads/master/MAINTAINERS.md
- https://github.com/prometheus/prometheus/blob/main/MAINTAINERS.md

**Describe alternatives you've considered**
- Adding this information to `CONTRIBUTING.md` instead.

**Additional context**
N/A

**Comment by dreinon** [comment]
Okay

**Comment by J0** [comment]
Sounds good to me

**Comment by dreinon** [comment]
@J0 codeowners is replaced by the maintainers.md?

**Comment by J0** [comment]
I think we can do without the codeowners file. Let me know if anyone feels that we need one though -- closing this issue for now.
